'use strict';

const crypto=require('crypto');
const stateMachine=require('./_payment_decision_state_machine');

const STAGING_BASE_ID='appZhq8nVZ7lZ2k6K';
const STAGING_CONFIRMATION='EXECUTE_PAYMENT_DECISION_IN_STAGING';
const SUPPORTED_MODES=new Set(['simulate','staging']);
const ACTION_PRIORITY=Object.freeze(['CREATE_PAYMENT_ONCE','CREATE_RECEIPT_RECORD_ONCE','RECALCULATE_ACCESS_ONLY','DELIVER_RECEIPT_ONLY','RELIMIT_EXACT_REJECTED_REPORT']);

function clean(value){return String(value??'').trim()}
function codedError(message,code,extra={}){return Object.assign(new Error(message),{code,...extra})}
function sha256(value){return crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex')}
function clone(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value))}
function environmentName(env=process.env){const explicit=clean(env.VLA_DATA_ENVIRONMENT).toLowerCase(),context=clean(env.CONTEXT).toLowerCase();return explicit||(context==='deploy-preview'||context==='branch-deploy'?'staging':context==='production'?'production':'local')}
function resolveExecutionContext({mode='simulate',confirmation='',env=process.env}={}){const normalized=clean(mode).toLowerCase()||'simulate';if(!SUPPORTED_MODES.has(normalized))throw codedError('Modo de ejecución no permitido.','PAYMENT_EXECUTION_MODE_INVALID',{mode:normalized});const environment=environmentName(env),baseId=clean(env.AIRTABLE_BASE_ID);if(normalized==='simulate')return{mode:'simulate',environment,baseId,canExecute:false};if(environment==='production'||clean(env.CONTEXT).toLowerCase()==='production')throw codedError('La ejecución productiva está bloqueada por diseño.','PAYMENT_EXECUTION_PRODUCTION_BLOCKED');if(environment!=='staging'||baseId!==STAGING_BASE_ID)throw codedError('La ejecución staging requiere el Base ID de pruebas exacto.','PAYMENT_EXECUTION_STAGING_MISMATCH',{environment,baseId});if(clean(confirmation)!==STAGING_CONFIRMATION)throw codedError('Falta la confirmación exacta de staging.','PAYMENT_EXECUTION_CONFIRMATION_REQUIRED');return{mode:'staging',environment,baseId,canExecute:true}}
function nextAction(machine){const available=stateMachine.nextActions(machine);return ACTION_PRIORITY.find(action=>available.includes(action))||null}
function eventId(machine,action,phase){return`PAYMENT_EXECUTION|${sha256({decisionId:machine?.decisionId,action,phase})}`}
function appendFailure(machine,action,error,at=new Date()){const timestamp=stateMachine.iso(at),detail=`${clean(error?.code)||'EXECUTION_FAILED'}: ${clean(error?.message||error)}`.slice(0,600);return{...clone(machine),lastError:detail,history:[...(machine?.history||[]),{state:machine?.state||'UNKNOWN',at:timestamp,detail:`${action}_FAILED: ${detail}`}]}}
function requiredFunction(object,name,code){const fn=object&&object[name];if(typeof fn!=='function')throw codedError(`Falta adaptador ${name}.`,code,{name});return fn}
async function audit(adapters,payload){const append=requiredFunction(adapters.audit,'append','PAYMENT_AUDIT_ADAPTER_REQUIRED');return append(payload)}
function adapterPayload(machine,action){const common={decisionId:machine.decisionId,source:machine.source,sourceId:machine.sourceId,reportId:machine.reportId,ownerId:machine.ownerId,adminId:machine.adminId,action};if(action==='CREATE_PAYMENT_ONCE')return{...common,idempotencyKey:machine.decisionId,paymentPayload:clone(machine.paymentPayload)};if(action==='CREATE_RECEIPT_RECORD_ONCE')return{...common,idempotencyKey:`${machine.decisionId}|RECEIPT`,paymentId:machine.paymentId};if(action==='DELIVER_RECEIPT_ONLY')return{...common,idempotencyKey:`${machine.decisionId}|DELIVERY`,paymentId:machine.paymentId,receiptId:machine.receiptId};if(action==='RECALCULATE_ACCESS_ONLY')return{...common,idempotencyKey:`${machine.decisionId}|ACCESS`,paymentId:machine.paymentId,receiptId:machine.receiptId};if(action==='RELIMIT_EXACT_REJECTED_REPORT')return{...common,idempotencyKey:`${machine.decisionId}|REVERSAL`,operationId:machine.provisionalOperationId};return common}
function applySuccess(machine,action,result,at){if(action==='CREATE_PAYMENT_ONCE')return stateMachine.recordPaymentCreated(machine,{paymentId:clean(result?.paymentId),at});if(action==='CREATE_RECEIPT_RECORD_ONCE')return stateMachine.recordReceiptOutcome(machine,{receiptId:clean(result?.receiptId),recorded:result?.recorded!==false,emailSent:result?.emailSent===true,error:result?.emailSent===true?'':clean(result?.emailError),at});if(action==='DELIVER_RECEIPT_ONLY')return stateMachine.recordReceiptDelivery(machine,{sent:result?.sent===true,error:clean(result?.error),at});if(action==='RECALCULATE_ACCESS_ONLY')return stateMachine.recordAccessOutcome(machine,{success:result?.success===true,status:clean(result?.status),error:clean(result?.error),at});if(action==='RELIMIT_EXACT_REJECTED_REPORT')return stateMachine.recordReversalOutcome(machine,{success:result?.success===true,status:clean(result?.status),error:clean(result?.error),at});throw codedError('Acción de ejecución desconocida.','PAYMENT_EXECUTION_ACTION_UNKNOWN',{action})}
function applyFailure(machine,action,error,at){if(action==='CREATE_RECEIPT_RECORD_ONCE')return stateMachine.recordReceiptOutcome(machine,{recorded:false,error:clean(error?.message||error),at});if(action==='DELIVER_RECEIPT_ONLY')return stateMachine.recordReceiptDelivery(machine,{sent:false,error:clean(error?.message||error),at});if(action==='RECALCULATE_ACCESS_ONLY')return stateMachine.recordAccessOutcome(machine,{success:false,error:clean(error?.message||error),at});if(action==='RELIMIT_EXACT_REJECTED_REPORT')return stateMachine.recordReversalOutcome(machine,{success:false,error:clean(error?.message||error),at});return appendFailure(machine,action,error,at)}
function actionAdapter(adapters,action){if(action==='CREATE_PAYMENT_ONCE')return requiredFunction(adapters.payment,'createOnce','PAYMENT_CREATE_ADAPTER_REQUIRED');if(action==='CREATE_RECEIPT_RECORD_ONCE')return requiredFunction(adapters.receipt,'recordOnce','RECEIPT_RECORD_ADAPTER_REQUIRED');if(action==='DELIVER_RECEIPT_ONLY')return requiredFunction(adapters.receipt,'deliver','RECEIPT_DELIVERY_ADAPTER_REQUIRED');if(action==='RECALCULATE_ACCESS_ONLY')return requiredFunction(adapters.access,'recalculate','ACCESS_RECALCULATE_ADAPTER_REQUIRED');if(action==='RELIMIT_EXACT_REJECTED_REPORT')return requiredFunction(adapters.access,'relimitExact','ACCESS_RELIMIT_ADAPTER_REQUIRED');throw codedError('Acción sin adaptador.','PAYMENT_EXECUTION_ACTION_UNKNOWN',{action})}
function createExecutor({adapters={},now=()=>new Date()}={}){
 async function executeNext(machine,{mode='simulate',confirmation='',env=process.env}={}){
  if(!machine||!clean(machine.decisionId))throw codedError('Falta una máquina de decisión válida.','PAYMENT_DECISION_MACHINE_REQUIRED');const context=resolveExecutionContext({mode,confirmation,env}),action=nextAction(machine);if(!action)return{ok:true,mode:context.mode,action:null,executed:false,simulated:context.mode==='simulate',machine:clone(machine),complete:true};const payload=adapterPayload(machine,action);if(context.mode==='simulate')return{ok:true,mode:'simulate',action,executed:false,simulated:true,payload,machine:clone(machine),complete:false};
  const startedAt=now(),before={eventId:eventId(machine,action,'BEFORE'),phase:'BEFORE',decisionId:machine.decisionId,action,at:stateMachine.iso(startedAt),payload:clone(payload)};
  try{await audit(adapters,before)}catch(error){return{ok:false,mode:'staging',action,executed:false,simulated:false,machine:appendFailure(machine,'AUDIT_BEFORE',error,startedAt),error:{code:clean(error?.code)||'AUDIT_BEFORE_FAILED',message:clean(error?.message||error)}}}
  const invoke=actionAdapter(adapters,action);let rawResult=null,nextMachine=null;
  try{rawResult=await invoke(clone(payload));nextMachine=applySuccess(machine,action,rawResult,now())}catch(error){nextMachine=applyFailure(machine,action,error,now());try{await audit(adapters,{eventId:eventId(machine,action,'FAILED'),phase:'FAILED',decisionId:machine.decisionId,action,at:stateMachine.iso(now()),error:{code:clean(error?.code)||'ADAPTER_FAILED',message:clean(error?.message||error)}})}catch(_){}return{ok:false,mode:'staging',action,executed:false,simulated:false,machine:nextMachine,error:{code:clean(error?.code)||'ADAPTER_FAILED',message:clean(error?.message||error)}}}
  let auditWarning='';try{await audit(adapters,{eventId:eventId(machine,action,'AFTER'),phase:'AFTER',decisionId:machine.decisionId,action,at:stateMachine.iso(now()),result:clone(rawResult),nextState:nextMachine.state})}catch(error){auditWarning=`${clean(error?.code)||'AUDIT_AFTER_FAILED'}: ${clean(error?.message||error)}`.slice(0,500)}
  return{ok:true,mode:'staging',action,executed:true,simulated:false,payload,result:clone(rawResult),machine:nextMachine,auditWarning,complete:nextAction(nextMachine)===null};
 }
 return{executeNext};
}

module.exports={STAGING_BASE_ID,STAGING_CONFIRMATION,SUPPORTED_MODES,ACTION_PRIORITY,clean,codedError,sha256,clone,environmentName,resolveExecutionContext,nextAction,eventId,appendFailure,requiredFunction,audit,adapterPayload,applySuccess,applyFailure,actionAdapter,createExecutor};
