'use strict';

const crypto=require('crypto');

const SCHEMA_VERSION=1;
const APPROVAL_SOURCE_REPORT='REPORT_APPROVAL';
const APPROVAL_SOURCE_CASH='CASH_DIRECT';
const PAYMENT_MODES=new Set(['USD','Bs BCV']);
const TERMINAL_STATES=new Set(['COMPLETED','REJECTED','REVERSED']);
const DECISION_INVARIANTS=Object.freeze({automaticApproval:false,paymentAction:'NONE',accessAction:'NONE',canCreatePayment:false,canEnableAccess:false,requiresAdminDecision:true});

function clean(value){return String(value??'').trim()}
function money(value){const number=Number(value);return Number.isFinite(number)?Math.round((number+Number.EPSILON)*100)/100:0}
function codedError(message,code,extra={}){return Object.assign(new Error(message),{code,...extra})}
function fieldsOf(record){return record&&record.fields?record.fields:record||{}}
function linkedIds(value){return Array.isArray(value)?value.map(item=>typeof item==='string'?item:item&&item.id).filter(Boolean):[]}
function choice(value){return clean(value&&typeof value==='object'&&value.name?value.name:value)}
function iso(value){const date=value instanceof Date?value:new Date(value);return Number.isFinite(date.getTime())?date.toISOString():''}
function sha256(value){return crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex')}
function clone(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value))}
function noExecution(){return{executed:false,airtableAction:'NONE',mkjAction:'NONE',emailAction:'NONE'}}
function assertAdmin(adminId){const value=clean(adminId);if(!value)throw codedError('Falta el administrador responsable.','DECISION_ADMIN_REQUIRED');return value}
function assertDecisionInvariants(decision){if(!decision||decision.preliminaryMatch!==true)throw codedError('El análisis no coincide preliminarmente.','DECISION_NOT_ELIGIBLE');for(const[key,expected]of Object.entries(DECISION_INVARIANTS))if(decision[key]!==expected)throw codedError(`La decisión viola ${key}.`,'DECISION_INVARIANT_FAILED',{key});return true}
function assertSnapshot(snapshot,snapshotValidation){if(!snapshot||snapshot.schemaVersion!==2||snapshot.balanceEngineVersion!==5||snapshot.cacheValid!==true)throw codedError('El snapshot financiero no es válido.','DECISION_SNAPSHOT_INVALID');if(snapshotValidation&&snapshotValidation.ok!==true)throw codedError('El snapshot financiero cambió.','DECISION_SNAPSHOT_CHANGED');if(Array.isArray(snapshot.paymentsAfterCutoff)&&snapshot.paymentsAfterCutoff.length)throw codedError('Existen pagos posteriores al corte.','DECISION_PAYMENTS_AFTER_CUTOFF');return true}
function normalizePaymentPayload(payload={}){const ownerId=clean(payload.ownerId),mode=choice(payload.mode),amountUsd=money(payload.amountUsd),amountBs=money(payload.amountBs),rate=Number(payload.rate||0),reference=clean(payload.reference).slice(0,160),date=clean(payload.date);if(!ownerId)throw codedError('Falta ownerId.','PAYMENT_OWNER_REQUIRED');if(!PAYMENT_MODES.has(mode))throw codedError('La forma de pago no es válida.','PAYMENT_MODE_INVALID');if(!(amountUsd>0))throw codedError('El monto USD referencial no es válido.','PAYMENT_AMOUNT_INVALID');if(mode==='Bs BCV'&&(!(amountBs>0)||!(rate>0)))throw codedError('El pago Bs requiere monto y tasa válidos.','PAYMENT_BS_INVALID');if(!reference)throw codedError('Falta referencia del pago.','PAYMENT_REFERENCE_REQUIRED');return{ownerId,mode,amountUsd,amountBs:mode==='Bs BCV'?amountBs:0,rate:mode==='Bs BCV'?rate:0,reference,date:date||null}}
function paymentFromReport(report,ownerId){const fields=fieldsOf(report),mode=choice(fields['Forma de Pago Reportada']||'Bs BCV'),amountUsd=money(fields['Equivalente USD Reportado']||fields['Monto Reportado']),amountBs=money(fields['Monto Reportado Bs']),rate=Number(fields['Tasa BCV Reporte']||0),reference=clean(fields.Referencia||'Reporte aprobado');return normalizePaymentPayload({ownerId,mode,amountUsd,amountBs,rate,reference,date:null})}
function approvalKey(payload){return`PAYMENT_DECISION|${sha256(payload)}`}
function baseMachine({source,sourceId,reportId=null,ownerId,adminId,paymentPayload,snapshotId='',authorizedAt,provisionalOperationId=''}){const identity={source,sourceId,reportId,ownerId,paymentPayload,snapshotId};return{schemaVersion:SCHEMA_VERSION,decisionId:approvalKey(identity),source,sourceId,reportId,ownerId,adminId,paymentPayload:clone(paymentPayload),snapshotId:clean(snapshotId),provisionalOperationId:clean(provisionalOperationId)||null,decision:'APPROVE',state:'PAYMENT_CREATE_PENDING',authorizedAt,paymentId:null,receiptId:null,receiptRecordStatus:'NOT_STARTED',receiptDeliveryStatus:'NOT_STARTED',accessRecalculationStatus:'NOT_STARTED',lastError:'',history:[{state:'PAYMENT_CREATE_PENDING',at:authorizedAt}],...noExecution()}}
function authorizeReportApproval({report,owner,adminId,decision,snapshot,snapshotValidation,now=new Date()}={}){const reportId=clean(report&&report.id),ownerId=clean(owner&&owner.id),admin=assertAdmin(adminId),fields=fieldsOf(report);if(!reportId||!ownerId)throw codedError('Falta reporte o propietario.','DECISION_LINK_MISSING');if(!linkedIds(fields['Propietario que Reporta']).includes(ownerId))throw codedError('El reporte no pertenece al propietario.','DECISION_OWNER_MISMATCH');const status=choice(fields.Estado||'Pendiente');if(status==='Confirmado'||fields['Pago Definitivo Creado']===true)throw codedError('El reporte ya tiene pago definitivo.','DECISION_PAYMENT_ALREADY_CREATED');if(status==='Rechazado')throw codedError('El reporte ya fue rechazado.','DECISION_ALREADY_REJECTED');assertDecisionInvariants(decision);assertSnapshot(snapshot,snapshotValidation);const authorizedAt=iso(now);if(!authorizedAt)throw codedError('Fecha de decisión inválida.','DECISION_DATE_INVALID');const paymentPayload=paymentFromReport(report,ownerId);return baseMachine({source:APPROVAL_SOURCE_REPORT,sourceId:reportId,reportId,ownerId,adminId:admin,paymentPayload,snapshotId:snapshot.snapshotId,authorizedAt,provisionalOperationId:fields['MKJ Operation ID']})}
function authorizeCashApproval({cashProposal,bcvRate=0,now=new Date()}={}){if(!cashProposal||cashProposal.type!=='DIRECT_ADMIN'||cashProposal.createsPayment!==true||cashProposal.reducesBalance!==true||cashProposal.executed!==false)throw codedError('La propuesta de efectivo no autoriza pago definitivo.','CASH_APPROVAL_INVALID');const authorizedAt=iso(now);if(!authorizedAt)throw codedError('Fecha de decisión inválida.','DECISION_DATE_INVALID');const isUsd=cashProposal.currency==='USD',rate=isUsd?0:Number(bcvRate||cashProposal.rate||cashProposal.bcvRate||0),amountBs=isUsd?0:money(cashProposal.amount),amountUsd=isUsd?money(cashProposal.amount):money(amountBs/rate);const paymentPayload=normalizePaymentPayload({ownerId:cashProposal.ownerId,mode:isUsd?'USD':'Bs BCV',amountUsd,amountBs,rate,reference:cashProposal.receiptReference,date:cashProposal.receivedAt});const sourceId=clean(cashProposal.idempotencyKey);if(!sourceId)throw codedError('La propuesta de efectivo no tiene clave idempotente.','CASH_IDEMPOTENCY_REQUIRED');return baseMachine({source:APPROVAL_SOURCE_CASH,sourceId,ownerId:paymentPayload.ownerId,adminId:assertAdmin(cashProposal.adminId),paymentPayload,snapshotId:'',authorizedAt})}
function authorizeRejection({report,owner,adminId,reason,now=new Date()}={}){const reportId=clean(report&&report.id),ownerId=clean(owner&&owner.id),admin=assertAdmin(adminId),why=clean(reason);if(!reportId||!ownerId)throw codedError('Falta reporte o propietario.','DECISION_LINK_MISSING');if(why.length<8)throw codedError('El rechazo requiere un motivo descriptivo.','REJECTION_REASON_REQUIRED');const fields=fieldsOf(report),status=choice(fields.Estado||'Pendiente');if(!linkedIds(fields['Propietario que Reporta']).includes(ownerId))throw codedError('El reporte no pertenece al propietario.','DECISION_OWNER_MISMATCH');if(fields['Pago Definitivo Creado']===true||status==='Confirmado')throw codedError('No se puede rechazar un reporte con pago definitivo.','REJECTION_PAYMENT_EXISTS');if(status==='Rechazado')throw codedError('El reporte ya fue rechazado.','DECISION_ALREADY_REJECTED');const at=iso(now);if(!at)throw codedError('Fecha de decisión inválida.','DECISION_DATE_INVALID');const provisional=fields['Habilitación Provisional Aplicada']===true&&clean(fields['MKJ Operation ID']);return{schemaVersion:SCHEMA_VERSION,decisionId:approvalKey({reportId,ownerId,decision:'REJECT',reason:why}),source:APPROVAL_SOURCE_REPORT,sourceId:reportId,reportId,ownerId,adminId:admin,decision:'REJECT',state:provisional?'REVERSAL_PENDING':'REJECTED',reason:why.slice(0,500),authorizedAt:at,paymentId:null,receiptId:null,paymentAction:'NONE',receiptAction:'NONE',accessAction:provisional?'RELIMIT_EXACT_REJECTED_REPORT':'NONE',provisionalOperationId:provisional?clean(fields['MKJ Operation ID']):null,history:[{state:provisional?'REVERSAL_PENDING':'REJECTED',at}],...noExecution()}}
function appendHistory(machine,state,at,detail=''){const history=[...(machine.history||[]),{state,at,detail:clean(detail)}];return{...machine,state,history}}
function assertApprovalMachine(machine){if(!machine||machine.decision!=='APPROVE')throw codedError('La operación no es una aprobación.','APPROVAL_MACHINE_REQUIRED');return true}
function recordPaymentCreated(machine,{paymentId,at=new Date()}={}){assertApprovalMachine(machine);const id=clean(paymentId),timestamp=iso(at);if(!id)throw codedError('Falta paymentId.','PAYMENT_ID_REQUIRED');if(machine.paymentId){if(machine.paymentId===id)return clone(machine);throw codedError('La aprobación ya está vinculada a otro pago.','PAYMENT_ALREADY_BOUND',{paymentId:machine.paymentId})}if(machine.state!=='PAYMENT_CREATE_PENDING')throw codedError('El pago no puede registrarse en este estado.','PAYMENT_TRANSITION_INVALID',{state:machine.state});return appendHistory({...machine,paymentId:id,receiptRecordStatus:'PENDING',receiptDeliveryStatus:'NOT_STARTED',accessRecalculationStatus:'NOT_STARTED'},'RECEIPT_RECORD_PENDING',timestamp,id)}
function recordReceiptOutcome(machine,{receiptId='',recorded=false,emailSent=false,error='',at=new Date()}={}){assertApprovalMachine(machine);if(!machine.paymentId)throw codedError('No existe pago definitivo vinculado.','RECEIPT_PAYMENT_REQUIRED');const timestamp=iso(at),id=clean(receiptId);if(machine.receiptId&&id&&machine.receiptId!==id)throw codedError('La aprobación ya está vinculada a otro recibo.','RECEIPT_ALREADY_BOUND',{receiptId:machine.receiptId});if(recorded&&!id&&!machine.receiptId)throw codedError('Falta receiptId registrado.','RECEIPT_ID_REQUIRED');if(machine.receiptId&&machine.receiptId===id&&machine.receiptRecordStatus==='RECORDED'&&((emailSent&&machine.receiptDeliveryStatus==='SENT')||(!emailSent&&machine.receiptDeliveryStatus!=='SENT')))return clone(machine);const receiptRecordStatus=recorded||machine.receiptId?'RECORDED':'PENDING',receiptDeliveryStatus=emailSent?'SENT':recorded?'FAILED':'NOT_STARTED',next={...machine,receiptId:machine.receiptId||id||null,receiptRecordStatus,receiptDeliveryStatus,lastError:clean(error).slice(0,500)};if(receiptRecordStatus!=='RECORDED')return appendHistory(next,'RECEIPT_RECORD_PENDING',timestamp,error);next.accessRecalculationStatus=next.accessRecalculationStatus==='DONE'?'DONE':'PENDING';return appendHistory(next,'ACCESS_RECALC_PENDING',timestamp,emailSent?'RECEIPT_SENT':'RECEIPT_RECORDED_DELIVERY_PENDING')}
function recordAccessOutcome(machine,{success=false,status='',error='',at=new Date()}={}){assertApprovalMachine(machine);if(!machine.paymentId)throw codedError('No existe pago definitivo vinculado.','ACCESS_PAYMENT_REQUIRED');if(machine.receiptRecordStatus!=='RECORDED')throw codedError('El recibo debe quedar registrado antes del recálculo de acceso.','ACCESS_RECEIPT_REQUIRED');if(success&&machine.accessRecalculationStatus==='DONE')return clone(machine);const timestamp=iso(at),accessRecalculationStatus=success?'DONE':'FAILED',next={...machine,accessRecalculationStatus,accessResult:clean(status),lastError:clean(error).slice(0,500)};if(!success)return appendHistory(next,'ACCESS_RECALC_PENDING',timestamp,error||status);const complete=next.receiptDeliveryStatus==='SENT';return appendHistory(next,complete?'COMPLETED':'COMPLETED_RECEIPT_DELIVERY_PENDING',timestamp,status)}
function recordReceiptDelivery(machine,{sent=false,error='',at=new Date()}={}){assertApprovalMachine(machine);if(machine.receiptRecordStatus!=='RECORDED'||!machine.receiptId)throw codedError('No existe recibo registrado para entregar.','RECEIPT_RECORD_REQUIRED');if(sent&&machine.receiptDeliveryStatus==='SENT')return clone(machine);const timestamp=iso(at),next={...machine,receiptDeliveryStatus:sent?'SENT':'FAILED',lastError:clean(error).slice(0,500)};const complete=sent&&next.accessRecalculationStatus==='DONE';return appendHistory(next,complete?'COMPLETED':next.accessRecalculationStatus==='DONE'?'COMPLETED_RECEIPT_DELIVERY_PENDING':'ACCESS_RECALC_PENDING',timestamp,sent?'RECEIPT_SENT':error)}
function nextActions(machine){if(!machine)return[];if(machine.decision==='REJECT')return machine.state==='REVERSAL_PENDING'?['RELIMIT_EXACT_REJECTED_REPORT']:[];if(machine.state==='COMPLETED')return[];if(machine.state==='PAYMENT_CREATE_PENDING')return['CREATE_PAYMENT_ONCE'];const actions=[];if(machine.receiptRecordStatus!=='RECORDED')actions.push('CREATE_RECEIPT_RECORD_ONCE');else if(machine.receiptDeliveryStatus!=='SENT')actions.push('DELIVER_RECEIPT_ONLY');if(machine.receiptRecordStatus==='RECORDED'&&machine.accessRecalculationStatus!=='DONE')actions.push('RECALCULATE_ACCESS_ONLY');return actions}
function evaluateRejectionReversal(machine,{owner,report}={}){if(!machine||machine.decision!=='REJECT'||machine.state!=='REVERSAL_PENDING')return{requestedAction:'NONE',reason:'REVERSAL_NOT_PENDING',executed:false};const ownerFields=fieldsOf(owner),reportFields=fieldsOf(report);if(clean(owner&&owner.id)!==machine.ownerId||clean(report&&report.id)!==machine.reportId)return{requestedAction:'NONE',reason:'ENTITY_MISMATCH',executed:false};if(reportFields['Pago Definitivo Creado']===true||choice(reportFields.Estado)==='Confirmado')return{requestedAction:'NONE',reason:'DEFINITIVE_PAYMENT_CREATED',executed:false};const current=linkedIds(ownerFields['Reporte Habilitante Actual']);if(current.length!==1||current[0]!==machine.reportId)return{requestedAction:'NONE',reason:'STALE_REPORT_REPLACED',executed:false};if(clean(reportFields['MKJ Operation ID'])!==machine.provisionalOperationId)return{requestedAction:'NONE',reason:'OPERATION_REPLACED',executed:false};return{requestedAction:'RELIMIT_EXACT_REJECTED_REPORT',reportId:machine.reportId,ownerId:machine.ownerId,operationId:machine.provisionalOperationId,executed:false,paymentAction:'NONE',receiptAction:'NONE',reason:'El reporte rechazado sigue siendo la autorización provisional exacta vigente.'}}
function recordReversalOutcome(machine,{success=false,status='',error='',at=new Date()}={}){if(machine&&machine.decision==='REJECT'&&machine.state==='REVERSED'&&success)return clone(machine);if(!machine||machine.decision!=='REJECT'||machine.state!=='REVERSAL_PENDING')throw codedError('No existe reversión pendiente.','REVERSAL_NOT_PENDING');const timestamp=iso(at);return appendHistory({...machine,reversalStatus:success?'DONE':'FAILED',lastError:clean(error).slice(0,500)},success?'REVERSED':'REVERSAL_PENDING',timestamp,status||error)}

module.exports={SCHEMA_VERSION,APPROVAL_SOURCE_REPORT,APPROVAL_SOURCE_CASH,PAYMENT_MODES,TERMINAL_STATES,DECISION_INVARIANTS,clean,money,codedError,fieldsOf,linkedIds,choice,iso,sha256,clone,noExecution,assertAdmin,assertDecisionInvariants,assertSnapshot,normalizePaymentPayload,paymentFromReport,approvalKey,baseMachine,authorizeReportApproval,authorizeCashApproval,authorizeRejection,appendHistory,assertApprovalMachine,recordPaymentCreated,recordReceiptOutcome,recordAccessOutcome,recordReceiptDelivery,nextActions,evaluateRejectionReversal,recordReversalOutcome};
