// netlify/functions/audit-history.js
// Consulta historial auditable con separación USD / Bs BCV.
// No crea registros técnicos API_USAGE para no consumir el límite de Airtable.

const { requireAdminCurrent } = require('./_auth');
const TABLES={propietarios:'Propietarios',historial:'Historial de Cargos',pagos:'Pagos'};
function buildUrl(baseId,tableName,query=''){return `https://api.airtable.com/v0/${baseId}/${encodeURIComponent(tableName)}${query}`;}
async function airtableGetAll(tableName,query,token,baseId,counter){let records=[];let offset=null;const safe=query||'';do{const sep=safe?'&':'?';const url=buildUrl(baseId,tableName,`${safe}${offset?`${sep}offset=${encodeURIComponent(offset)}`:''}`);counter.calls+=1;const response=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||data.message||`Error cargando ${tableName}`);records=records.concat(data.records||[]);offset=data.offset;}while(offset);return records;}
function monthKeyFromDate(d){return d?String(d).slice(0,7):'';}
function monthKeysBack(count){const keys=[];const now=new Date();for(let i=0;i<count;i++){const d=new Date(now.getFullYear(),now.getMonth()-i,1);keys.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);}return keys;}
function parseAuditConcept(concept){const parts=String(concept||'').split('|');if(parts.length<4||parts[0]!=='AUDITORIA')return null;return{month:parts[1],casa:parts[2],label:parts.slice(3).join('|')};}
function num(v){return Math.round(Number(v||0)*100)/100;}
function status(balance){if(balance>0.01)return'Deuda';if(balance<-0.01)return'Saldo a favor';return'Solvente';}
function empty(month){return{month,hasSnapshot:false,saldoInicialUsd:null,saldoInicialBsRef:null,cargosUsd:null,cargosBsRef:null,pagosUsd:null,pagosBsRef:null,saldoFinalUsd:null,saldoFinalBsRef:null,saldoFinalTotal:null,estado:'Sin corte registrado',movements:[]};}
function summarize(month,movements){const s=empty(month);s.hasSnapshot=movements.length>0;s.movements=movements;movements.forEach(m=>{const label=String(m.label||'').toLowerCase();const amount=num(m.amount);if(label.includes('saldo inicial usd'))s.saldoInicialUsd=amount;else if(label.includes('saldo inicial bs'))s.saldoInicialBsRef=amount;else if(label.includes('cargos usd'))s.cargosUsd=amount;else if(label.includes('cargos bs'))s.cargosBsRef=amount;else if(label.includes('pagos usd'))s.pagosUsd=amount;else if(label.includes('pagos bs'))s.pagosBsRef=amount;else if(label.includes('saldo final usd'))s.saldoFinalUsd=amount;else if(label.includes('saldo final bs'))s.saldoFinalBsRef=amount;else if(label.includes('saldo final total')){s.saldoFinalTotal=amount;s.estado=status(amount);}});return s;}
exports.handler=async function(event){
  const auth=await requireAdminCurrent(event); if(!auth.ok)return auth.response;
  const {AIRTABLE_API_TOKEN,AIRTABLE_BASE_ID}=process.env;const counter={calls:0};
  if(!AIRTABLE_API_TOKEN||!AIRTABLE_BASE_ID)return{statusCode:500,body:JSON.stringify({message:'Airtable no está configurado.'})};
  try{const params=event.queryStringParameters||{};const ownerId=params.ownerId;const monthsCount=Math.min(Math.max(parseInt(params.months||'6',10)||6,1),12);if(!ownerId)return{statusCode:400,body:JSON.stringify({message:'Debe indicar ownerId.'})};const [owners,auditRecords,pagos]=await Promise.all([airtableGetAll(TABLES.propietarios,'',AIRTABLE_API_TOKEN,AIRTABLE_BASE_ID,counter),airtableGetAll(TABLES.historial,`?filterByFormula=${encodeURIComponent(`IFERROR(FIND('AUDITORIA|', {Concepto}), 0)`)}`,AIRTABLE_API_TOKEN,AIRTABLE_BASE_ID,counter),airtableGetAll(TABLES.pagos,'',AIRTABLE_API_TOKEN,AIRTABLE_BASE_ID,counter)]);const owner=owners.find(r=>r.id===ownerId);if(!owner)return{statusCode:404,body:JSON.stringify({message:'Propietario no encontrado.'})};const months=monthKeysBack(monthsCount);const grouped=Object.fromEntries(months.map(m=>[m,[]]));auditRecords.forEach(record=>{const f=record.fields||{};if(!((f.Propietario||[]).includes(ownerId)))return;const parsed=parseAuditConcept(f.Concepto);if(!parsed||!grouped[parsed.month])return;grouped[parsed.month].push({id:record.id,month:parsed.month,label:parsed.label,concept:f.Concepto,amount:num(f['Monto Cargado']),date:f.Fecha||null});});const summaries=months.map(month=>summarize(month,grouped[month].sort((a,b)=>String(a.concept).localeCompare(String(b.concept)))));const ownerPayments=pagos.filter(p=>(p.fields?.['Propietario que Paga']||[]).includes(ownerId)).map(p=>({id:p.id,month:monthKeyFromDate(p.fields?.['Fecha de Pago']),date:p.fields?.['Fecha de Pago'],amount:num(p.fields?.['Monto Pagado']),amountBs:num(p.fields?.['Monto Pagado Bs']),rate:num(p.fields?.['Tasa BCV Aplicada']),equivalentUsd:num(p.fields?.['Equivalente USD Aplicado']||p.fields?.['Monto Pagado']),mode:p.fields?.['Forma de Pago']||'Bs BCV',method:p.fields?.['Método de Pago']||'',reference:p.fields?.['ID de Pago']||''})).filter(p=>months.includes(p.month));return{statusCode:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store, no-cache, must-revalidate','X-Airtable-Calls':String(counter.calls)},body:JSON.stringify({generatedAt:new Date().toISOString(),owner:{id:owner.id,...(owner.fields||{})},months:summaries,payments:ownerPayments})};}catch(error){return{statusCode:500,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Airtable-Calls':String(counter.calls)},body:JSON.stringify({message:'Error consultando historial de auditoría.',detail:error.message})};}
};