(function(){
  'use strict';
  const state={recipients:[],selected:new Set(),active:null};
  const $=id=>document.getElementById(id);
  function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
  function money(value){return '$'+Number(value||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}
  function token(){return window.vlaAdminSession?.token()||localStorage.getItem('vla-admin-token')||sessionStorage.getItem('vla-admin-token')||'';}
  function authHeaders(){return {'Content-Type':'application/json','Authorization':'Bearer '+token()};}
  function toast(message,error=false){const host=$('toast');host.textContent=message;host.className='toast '+(error?'error':'success');clearTimeout(toast.timer);toast.timer=setTimeout(()=>host.classList.add('hidden'),4200);}
  async function adminFetch(url,options={}){const response=await fetch(url,{...options,headers:{...authHeaders(),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(response.status===401){window.vlaAdminSession?.clear();showLogin();throw new Error('Sesión vencida. Inicie sesión nuevamente.');}if(!response.ok)throw new Error(data.detail||data.message||`Error ${response.status}`);return data;}
  async function login(event){event.preventDefault();$('login-error').classList.add('hidden');try{const response=await fetch('/.netlify/functions/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.message||'Contraseña incorrecta.');localStorage.setItem('vla-admin-auth','true');localStorage.setItem('vla-admin-token',data.token);sessionStorage.setItem('vla-admin-auth','true');sessionStorage.setItem('vla-admin-token',data.token);showApp();await loadPreview();}catch(error){$('login-error').textContent=error.message;$('login-error').classList.remove('hidden');}}
  function showLogin(){$('app').classList.add('hidden');$('login').classList.remove('hidden');}
  function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');}
  function validationBadge(item){if(item.errors.length)return `<span class="badge bad">Bloqueada</span><small>${esc(item.errors[0])}</small>`;if(!item.sendable)return `<span class="badge neutral">Sin obligación</span><small>${esc(item.warnings[0]||'No seleccionable')}</small>`;return '<span class="badge ok">Lista para simular</span><small>Fotografía válida</small>';}
  function renderRecipients(){const body=$('recipients-body');body.innerHTML=state.recipients.map(item=>`<tr class="${item.errors.length?'blocked':''}"><td><input class="recipient-check" type="checkbox" data-house="${item.house}" ${state.selected.has(item.house)?'checked':''} ${item.sendable?'':'disabled'} aria-label="Seleccionar Casa ${item.house}"></td><td><strong>Casa ${item.house}</strong></td><td>${esc(item.ownerName)}</td><td><span class="mono">${esc(item.phoneMasked||'No válido')}</span></td><td>${money(item.payableUsd)}</td><td>${money(item.payableBsRef)}</td><td>${money(item.internalSurchargeBsRef)}</td><td><strong>${money(item.payableTotalRef)}</strong></td><td><div class="validation">${validationBadge(item)}</div></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No hay datos disponibles.</td></tr>';body.querySelectorAll('.recipient-check').forEach(input=>input.addEventListener('change',()=>toggleHouse(Number(input.dataset.house),input.checked)));}
  function selectedItems(){return state.recipients.filter(item=>state.selected.has(item.house));}
  function updateSelection(){const items=selectedItems(),total=items.reduce((sum,item)=>sum+Number(item.payableTotalRef||0),0);$('selected-count').textContent=`${items.length} seleccionado${items.length===1?'':'s'}`;$('selected-total').textContent=`${money(total)} referenciales`;$('review-selection').disabled=!items.length;renderPreviewSelector(items);renderRecipients();}
  function toggleHouse(house,checked){if(checked)state.selected.add(house);else state.selected.delete(house);updateSelection();}
  function renderPreviewSelector(items){const select=$('preview-selector');const prior=Number(select.value||0);select.innerHTML=items.map(item=>`<option value="${item.house}">Casa ${item.house} · ${esc(item.ownerName)}</option>`).join('');if(items.some(item=>item.house===prior))select.value=String(prior);state.active=items.find(item=>item.house===Number(select.value))||items[0]||null;renderActivePreview();}
  function renderActivePreview(){const item=state.active;$('preview-empty').classList.toggle('hidden',Boolean(item));$('preview-card').classList.toggle('hidden',!item);if(!item)return;$('preview-owner').textContent=`Casa ${item.house} · ${item.ownerName}`;$('preview-phone').textContent=item.phoneMasked;$('preview-hash').textContent=item.snapshotHash.slice(0,16)+'…';$('preview-message').textContent=item.message;}
  function switchSection(name){document.querySelectorAll('.panel').forEach(panel=>panel.classList.remove('active-section'));$(`${name}-section`)?.classList.add('active-section');document.querySelectorAll('.nav-item[data-section]').forEach(button=>button.classList.toggle('active',button.dataset.section===name));if(name==='preview')renderActivePreview();}
  async function loadPreview(){setFeedback('Actualizando fotografía oficial…');try{const data=await adminFetch('/.netlify/functions/messaging-preview');if(data.totalOwners!==15)throw new Error(`Se recibieron ${data.totalOwners||0} casas; se esperaban 15.`);state.recipients=data.recipients||[];state.selected=new Set([...state.selected].filter(house=>state.recipients.some(item=>item.house===house&&item.sendable)));$('metric-total').textContent=data.totalOwners;$('metric-sendable').textContent=data.sendableCount;$('metric-blocked').textContent=data.blockedCount;renderRecipients();updateSelection();setFeedback(`Fotografía oficial generada con motor v${data.balanceEngineVersion}.`,false);}
    catch(error){state.recipients=[];state.selected.clear();renderRecipients();updateSelection();setFeedback(error.message,true);toast(error.message,true);}}
  function setFeedback(message,error=false){const host=$('global-feedback');host.textContent=message;host.className='feedback '+(error?'error':'ok');}
  function exportSimulation(){const items=selectedItems();if(!items.length)return;const payload={exportedAt:new Date().toISOString(),mode:'SIMULACION_SIN_ENVIO',recipients:items};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`VLA_simulacion_whatsapp_${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Simulación exportada. No se envió ningún mensaje.');}
  function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('vla-wa-theme',theme);$('theme').textContent=theme==='dark'?'☀':'◐';}
  $('login-form').addEventListener('submit',login);$('refresh').addEventListener('click',loadPreview);$('select-all').addEventListener('click',()=>{state.recipients.filter(item=>item.sendable).forEach(item=>state.selected.add(item.house));updateSelection();});$('clear-selection').addEventListener('click',()=>{state.selected.clear();updateSelection();});$('review-selection').addEventListener('click',()=>switchSection('preview'));$('preview-selector').addEventListener('change',()=>{state.active=selectedItems().find(item=>item.house===Number($('preview-selector').value))||null;renderActivePreview();});$('copy-message').addEventListener('click',async()=>{if(!state.active)return;try{await navigator.clipboard.writeText(state.active.message);toast('Mensaje copiado.');}catch{toast('No se pudo copiar automáticamente.',true);}});$('export-simulation').addEventListener('click',exportSimulation);$('theme').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));$('logout').addEventListener('click',()=>{window.vlaAdminSession?.clear();location.href='/admin.html';});document.querySelectorAll('.nav-item[data-section]:not(:disabled)').forEach(button=>button.addEventListener('click',()=>switchSection(button.dataset.section)));
  applyTheme(localStorage.getItem('vla-wa-theme')||'light');if(token()){showApp();loadPreview();}else showLogin();
})();
