'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const reconciliation=require('../netlify/functions/_shared/_access_reconciliation_readonly');
const mkj=require('../netlify/functions/_shared/_mkj_client');

function owner(house){return{id:`recOwner${String(house).padStart(9,'0')}`,fields:{Casa:house,Propietario:`Casa ${house}`,'MKJ User ID':String(8000+house),'MKJ Email':`casa${house}@test.local`,'Estado Acceso Portón':house===3?'Limitado':'Habilitado','Excepción Acceso':false,'Última Sync MKJ':'2026-08-08 10:00:00'}}}
function remote(house,active=house!==3){return{membership:{active,updated_at:'2026-08-08T14:00:00Z'},user:{id:String(8000+house),email:`casa${house}@test.local`}}}
function deps(overrides={}){return{getAccessMode:async()=>({mode:'Automático'}),loadAccessContext:async()=>({owners:Array.from({length:15},(_,index)=>owner(index+1)),pagos:[],reportes:[],gastos:[]}),calculateExpiredAccessDebt:item=>({hasExpiredDebt:Number(item.fields.Casa)===3,expiredUsd:Number(item.fields.Casa)===3?20:0,expiredBsRef:0}),getAutomationRules:async()=>({rules:{payment:{dueDay:10,surchargeRate:.1}}}),mkjLogin:async()=>({token:'fixture'}),listOrganizationUsers:async()=>({users:Array.from({length:15},(_,index)=>remote(index+1))}),listOrganizationDetailUsers:async()=>({users:[]}),resolveOrganizationUser:mkj.resolveOrganizationUser,...overrides}}

test('reconcilia 15/15 sin ejecutar escrituras',async()=>{const result=await reconciliation.runReadOnlyReconciliation(deps());assert.equal(result.readOnly,true);assert.equal(result.total,15);assert.equal(result.reconciled,15);assert.equal(result.coherent,15);assert.equal(result.discrepancyCount,0);assert.equal(result.rows[2].estadoEsperadoVla,'Limitado');assert.equal(result.rows[2].estadoMkj,'Limitado')});
test('reporta ID obsoleto y discrepancia remota sin corregirlos',async()=>{const owners=Array.from({length:15},(_,index)=>owner(index+1));owners[7].fields['MKJ User ID']='old-id';const result=await reconciliation.runReadOnlyReconciliation(deps({loadAccessContext:async()=>({owners,pagos:[],reportes:[],gastos:[]}),listOrganizationUsers:async()=>({users:Array.from({length:15},(_,index)=>remote(index+1,index===7?false:index+1!==3))})}));const house8=result.rows[7];assert.equal(house8.mkjResolvedUserId,'8008');assert(house8.discrepancias.includes('STALE_MEMBER_ID'));assert(house8.discrepancias.includes('MKJ_EXPECTATION_MISMATCH'));assert.match(house8.accionRecomendada,/MKJ User ID/)});
test('modo Manual conserva discrepancias informativas para Health sin mutar',async()=>{const result=await reconciliation.runReadOnlyReconciliation(deps({getAccessMode:async()=>({mode:'Manual'}),listOrganizationUsers:async()=>({users:Array.from({length:15},(_,index)=>remote(index+1,index===0?false:index+1!==3))})}));assert.equal(result.mode,'Manual');assert.equal(result.discrepancyCount,1);assert.equal(result.rows[0].estadoMkj,'Limitado')});
test('interpreta estados activos, inactivos y desconocidos de varias formas MKJ',()=>{assert.equal(reconciliation.remoteAccessState({membership:{active:true}}),'Habilitado');assert.equal(reconciliation.remoteAccessState({membership:{disabled:true}}),'Limitado');assert.equal(reconciliation.remoteAccessState({status:'inactive'}),'Limitado');assert.equal(reconciliation.remoteAccessState({user:{email:'x@test'}}),'Desconocido')});
test('prioriza el detalle de organización cuando contiene un estado más completo',async()=>{const general=Array.from({length:15},(_,index)=>({user:{id:String(8001+index),email:`casa${index+1}@test.local`}})),detail=Array.from({length:15},(_,index)=>remote(index+1,index===0?false:index+1!==3)),result=await reconciliation.runReadOnlyReconciliation(deps({listOrganizationUsers:async()=>({users:general}),listOrganizationDetailUsers:async()=>({users:detail})}));assert.equal(result.rows[0].estadoMkj,'Limitado');assert(result.rows[0].discrepancias.includes('MKJ_EXPECTATION_MISMATCH'));assert.equal(result.rows[2].estadoMkj,'Limitado')});
test('la implementación read-only no contiene primitivas de escritura',()=>{const shared=fs.readFileSync('netlify/functions/_shared/_access_reconciliation_readonly.js','utf8'),endpoint=fs.readFileSync('netlify/functions/access-reconciliation-readonly.js','utf8');for(const forbidden of ['mkjSetMemberStatus','airtablePatchRecord','airtableCreateRecord','method:\'PUT\'','method:\'PATCH\'','method:\'POST\''])assert(!shared.includes(forbidden)&&!endpoint.includes(forbidden),`La reconciliación incluyó ${forbidden}`)});
