'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.join(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const admin=read('admin.html');
const premium=read('admin-premium.js');
const controls=read('admin-premium-controls.js');
const preflight=read('admin-premium-preflight.js');
const css=read('admin-premium.css');
const polish=read('admin-premium-polish.css');
const bridge=read('admin-session-bridge.js');
const edge=read('netlify/edge-functions/admin-premium-assets.js');
const legacy=read('netlify/edge-functions/admin-links.js');
const netlify=read('netlify.toml');
assert(admin.includes('admin-manual-payment'));
assert(admin.includes('admin-expense'));
assert(admin.includes('process-payment-report'));
assert(admin.includes('monthly-close'));
assert(premium.includes('vla-premium-shell'));
assert(premium.includes('vla-dashboard-panels'));
assert(premium.includes('vla-dashboard-reports'));
assert(premium.includes('system-health-advanced'));
assert(premium.includes('access-mode'));
assert(premium.includes('handleReport'));
assert(!premium.includes('functions/airtable/'));
assert(css.includes('#vla-premium-sidebar'));
assert(css.includes('@media(max-width:1024px)'));
assert(polish.includes('#api-restan'));
assert(polish.includes('-webkit-line-clamp:2'));
assert(controls.includes('vla-admin-theme'));
assert(controls.includes('/mkj-access.html'));
assert(preflight.includes('vla-premium-preflight'));
assert(preflight.includes('data-status'));
assert(bridge.includes('localStorage'));
assert(bridge.includes('sessionStorage'));
assert(bridge.includes('response.status===401'));
assert(edge.includes('admin-session-bridge.js'));
assert(edge.includes('admin-premium-preflight.js'));
assert(edge.includes('admin-premium.css'));
assert(edge.includes('admin-premium-polish.css'));
assert(edge.includes('admin-premium.js'));
assert(edge.includes('window.ready===true'));
assert(edge.includes('single-login-v1'));
assert(edge.includes('premium-v1'));
assert(!legacy.includes('vla-admin-visual-refresh-v1'));
assert(legacy.includes('native-protected-ui'));
assert(netlify.includes('admin-premium-assets'));
new vm.Script(premium,{filename:'admin-premium.js'});
new vm.Script(controls,{filename:'admin-premium-controls.js'});
new vm.Script(preflight,{filename:'admin-premium-preflight.js'});
new vm.Script(bridge,{filename:'admin-session-bridge.js'});
console.log('ADMIN_PREMIUM_STATIC_TESTS_OK');
