'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.join(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const admin=read('admin.html');
const premium=read('admin-premium.js');
const premiumTen=read('admin-premium-10.js');
const controls=read('admin-premium-controls.js');
const preflight=read('admin-premium-preflight.js');
const css=read('admin-premium.css');
const cssTen=read('admin-premium-10.css');
const polish=read('admin-premium-polish.css');
const bridge=read('admin-session-bridge.js');
const edge=read('netlify/edge-functions/admin-premium-assets.js');
const authEdge=read('netlify/edge-functions/admin-auth-version.js');
const legacy=read('netlify/edge-functions/admin-links.js');
const netlify=read('netlify.toml');
assert(admin.includes('admin-manual-payment'));
assert(admin.includes('admin-expense'));
assert(admin.includes('process-payment-report'));
assert(admin.includes('monthly-close'));
assert(premium.includes('vla-premium-shell'));
assert(premium.includes('vla-dashboard-panels'));
assert(premium.includes('vla-dashboard-reports'));
assert(premium.includes('system-health-advanced'));
assert(premium.includes('access-mode'));
assert(premium.includes('handleReport'));
assert(!premium.includes('functions/airtable/'));
assert(css.includes('#vla-premium-sidebar'));
assert(css.includes('@media(max-width:1024px)'));
assert(polish.includes('#api-restan'));
assert(polish.includes('-webkit-line-clamp:3'));
assert(polish.includes('#login input{font-size:16px'));
assert(controls.includes('vla-admin-theme'));
assert(controls.includes('/mkj-access.html'));
assert(preflight.includes('vla-premium-preflight'));
assert(preflight.includes('data-status'));
assert(bridge.includes('localStorage'));
assert(bridge.includes('sessionStorage'));
assert(bridge.includes('response.status===401'));
assert(edge.includes('admin-session-bridge.js'));
assert(edge.includes('admin-premium-preflight.js'));
assert(edge.includes('admin-premium.css'));
assert(edge.includes('admin-premium-polish.css'));
assert(edge.includes('admin-premium-10.css'));
assert(edge.includes('admin-premium-10.js'));
assert(edge.includes('admin-feature-parity.js'));
assert(edge.includes('vla-admin-quality'));
assert(edge.includes('window.ready===true'));
assert(edge.includes('single-login-v1'));
assert(edge.includes('premium-v1'));
assert(cssTen.includes('#vla-owner-intelligence'));
assert(cssTen.includes('.vla-amount-debt'));
assert(cssTen.includes('.vla-amount-ok'));
assert(cssTen.includes('#vla-reading-controls'));
assert(cssTen.includes('font-size:calc(14px * var(--vla-reading-scale))'));
assert(premiumTen.includes('protectedRunClose'));
assert(premiumTen.includes('protectedHandleReport'));
assert(premiumTen.includes('vla-owner-toolbar'));
assert(premiumTen.includes('vla-status-overview'));
assert(authEdge.includes('ADMIN_AUTH_CONFIG|'));
assert(authEdge.includes('sessionRevoked'));
assert(!legacy.includes('vla-admin-visual-refresh-v1'));
assert(legacy.includes('native-protected-ui'));
assert(netlify.includes('admin-premium-assets'));
assert(netlify.includes('admin-auth-version'));
new vm.Script(premium,{filename:'admin-premium.js'});
new vm.Script(premiumTen,{filename:'admin-premium-10.js'});
new vm.Script(controls,{filename:'admin-premium-controls.js'});
new vm.Script(preflight,{filename:'admin-premium-preflight.js'});
new vm.Script(bridge,{filename:'admin-session-bridge.js'});
console.log('ADMIN_PREMIUM_STATIC_TESTS_OK');
