'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const consensus=require('../netlify/functions/_shared/_payment_ai_consensus');
const admin=require('../netlify/functions/_shared/_payment_admin_decision');
const automation=require('../netlify/functions/_shared/_payment_report_automation');
const background=require('../netlify/functions/payment-report-analyzer-background');

function analysis(overrides={}){return{method:'ZELLE',bank_or_platform:'Bank of America',amount:50,currency:'USD',transaction_date:'2026-08-22',transaction_time:'12:30:00',reference:'bmbgcr3r',transaction_status:'SENT',recipient_name:'ENZO PANARITO',recipient_phone:null,recipient_email:'enzopanarito@gmail.com',recipient_account_visible:null,recipient_account_last4:null,recipient_document:null,recipient_binance_id:null,sender_name:'JESUS GOYO',sender_account_visible:null,memo:null,confidence:0.99,critical_fields_visible:true,warnings:[],possible_visual_modification:false,...overrides}}

test('dos análisis idénticos y >=97% producen consenso',()=>{const result=consensus.compareAnalyses(analysis(),analysis(),0.97);assert.equal(result.passed,true);assert(result.sharedRecipientEvidence.includes('email:enzopanarito@gmail.com'));assert.equal(result.recipientConsensusMode,'STRONG')});
test('cualquier discrepancia crítica bloquea consenso',()=>{for(const changed of [{amount:49.98},{reference:'OTRA'},{transaction_date:'2026-08-21'},{recipient_name:'OTRO',recipient_email:'otro@example.com'},{confidence:0.96}]){const result=consensus.compareAnalyses(analysis(),analysis(changed),0.97);assert.equal(result.passed,false)}});
test('mismo nombre nunca compensa un identificador fuerte contradictorio',()=>{const result=consensus.compareAnalyses(analysis(),analysis({recipient_name:'ENZO PANARITO',recipient_email:'otro@example.com'}),0.97);assert.equal(result.passed,false);assert(result.recipientConflicts.includes('email'));assert(result.failedChecks.includes('RECIPIENT_IDENTITY'))});
test('nombre idéntico solo sirve cuando ninguno de los dos modelos ve un identificador fuerte',()=>{const a=analysis({recipient_email:null}),b=analysis({recipient_email:null});const result=consensus.compareAnalyses(a,b,0.97);assert.equal(result.passed,true);assert.equal(result.recipientConsensusMode,'NAME_ONLY')});
test('si solo un modelo ve identificador fuerte, autopago queda bloqueado por asimetría',()=>{const result=consensus.compareAnalyses(analysis(),analysis({recipient_email:null}),0.97);assert.equal(result.passed,false);assert(result.recipientConflicts.includes('email'))});
test('aprobación automática exige consenso persistido y receptor compartido',()=>{const base={'Fecha Operación Detectada':'2026-08-22','Fuente Fecha Operación':'PROOF_EXTRACTED','Fecha Requiere Revisión':false,'Archivo Obligatorio':true,'Nivel de Duplicado':'none','Posible Duplicado':false,'Clasificación Receptor':'CONFIRMED','Normalized Analysis JSON':JSON.stringify(analysis()),'Estado Transacción Detectado':'SENT','Resultado Validación':'Coincidencia exacta verificada'};assert(admin.normalApprovalBlockers(base,{automatic:true}).includes('AI_CONSENSUS_NOT_VERIFIED'));const good={...base,'Rules Evaluation JSON':JSON.stringify({aiConsensus:{passed:true,minimumConfidence:0.97,primaryConfidence:0.99,secondaryConfidence:0.99,sharedRecipientEvidence:['email:enzopanarito@gmail.com']}})};assert.deepStrictEqual(admin.normalApprovalBlockers(good,{automatic:true}),[])});
test('fallo servidor conserva prelectura y deja causa explícita',()=>{const prior={fields:{'Normalized Analysis JSON':JSON.stringify({stage:'prefill',confidence:0.95,recipient:'ENZO PANARITO'}),'AI Confidence':0.95,'AI Provider Principal':'Prelectura · gemini-3.5-flash-lite','Fecha Operación Detectada':'2026-08-22','Fuente Fecha Operación':'PROOF_EXTRACTED','Confianza Fecha Operación':'HIGH','Fecha Requiere Revisión':false,'Evidencia Fecha Operación':'Fecha visible extraída del comprobante.'}};const fields=automation.resultFields({ok:false,reason:'TIMEOUT',detail:'Gemini excedió el límite.',processingState:'Revisión manual urgente',resultValidation:'Revisión manual urgente',processingAttempts:2},prior);assert.match(fields['Normalized Analysis JSON'],/prefill/);assert.equal(fields['AI Confidence'],0.95);assert.equal(fields['AI Failure Reason'],'TIMEOUT');assert.match(fields['Último Error de Procesamiento'],/TIMEOUT/);assert.equal(fields['Intentos de Procesamiento'],2);assert.notEqual(fields['Rules Evaluation JSON'],'{}')});
test('background clasifica fallos transitorios para reintento nativo',()=>{for(const code of ['TIMEOUT','RATE_LIMIT','PROVIDER_UNAVAILABLE','EMPTY_OUTPUT','PROCESSING_CAS_CONFLICT','BLOBS_UNAVAILABLE'])assert.equal(background.retryable(code),true);for(const code of ['AI_AUTH_FAILED','RECIPIENT_MISMATCH','LOW_CONFIDENCE'])assert.equal(background.retryable(code),false)});
test('configuración explícita no puede ser sobreescrita por discovery',()=>{const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_shared','_payment_report_automation.js'),'utf8');assert(!/if\(models\[0\]\)configuredAi\.primaryModel=models\[0\]/.test(source));assert.match(source,/if\(!configuredAi\.primaryModel&&models\[0\]\)configuredAi\.primaryModel=models\[0\]/);assert(!/configuredAi\.secondaryEnabled=true/.test(source))});
test('orquestador exige consenso antes de entregar automaticApproval al árbitro',()=>{const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_shared','_payment_processing_orchestrator.js'),'utf8');assert.match(source,/automaticApprovalEnabled:config\.automaticApprovalEnabled&&aiConsensus\.passed===true/);assert.match(source,/secondary-consensus/);assert.match(source,/retryDelayMs/)});
