'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const admin=require('../netlify/functions/_shared/_payment_admin_decision');
const automation=require('../netlify/functions/_shared/_payment_report_automation');
const background=require('../netlify/functions/payment-report-analyzer-background');

function analysis(overrides={}){return{method:'ZELLE',bank_or_platform:'Bank of America',amount:50,currency:'USD',transaction_date:'2026-08-22',transaction_time:'12:30:00',reference:'bmbgcr3r',transaction_status:'COMPLETED',recipient_name:'ENZO PANARITO',recipient_phone:null,recipient_email:'enzopanarito@gmail.com',recipient_account_visible:null,recipient_account_last4:null,recipient_document:null,recipient_binance_id:null,sender_name:'JESUS GOYO',sender_account_visible:null,memo:null,confidence:0.99,critical_fields_visible:true,warnings:[],possible_visual_modification:false,...overrides}}
function autoBase(){return{'Fecha Operación Detectada':'2026-08-22','Fuente Fecha Operación':'PROOF_EXTRACTED','Fecha Requiere Revisión':false,'Archivo Obligatorio':true,'Nivel de Duplicado':'none','Posible Duplicado':false,'Clasificación Receptor':'CONFIRMED','Normalized Analysis JSON':JSON.stringify(analysis()),'Estado Transacción Detectado':'COMPLETED','Resultado Validación':'Coincidencia exacta verificada','Forma de Pago Reportada':'USD','Monto Reportado':50,'Equivalente USD Reportado':50,'Monto Detectado':50,'Referencia':'bmbgcr3r','Referencia Detectada':'BMBGCR3R'}}

test('aprobación automática conserva validación redundante de monto y referencia sin exigir doble modelo',()=>{const base=autoBase();assert.deepStrictEqual(admin.normalApprovalBlockers(base,{automatic:true}),[]);assert(admin.normalApprovalBlockers({...base,Referencia:'OTRA'},{automatic:true}).includes('REPORTED_REFERENCE_MISMATCH'));assert(admin.normalApprovalBlockers({...base,'Monto Detectado':49.98},{automatic:true}).includes('REPORTED_AMOUNT_MISMATCH'))});
test('solo COMPLETED puede materializar autopago; SENT y PROCESSED quedan en revisión',()=>{const base=autoBase();for(const status of ['SENT','PROCESSED'])assert(admin.normalApprovalBlockers({...base,'Estado Transacción Detectado':status},{automatic:true}).includes('AUTOMATIC_STATUS_NOT_COMPLETED'));assert(!admin.normalApprovalBlockers(base,{automatic:true}).includes('AUTOMATIC_STATUS_NOT_COMPLETED'))});
test('fallo servidor conserva prelectura y deja causa explícita',()=>{const prior={fields:{'Normalized Analysis JSON':JSON.stringify({stage:'prefill',confidence:0.95,recipient:'ENZO PANARITO'}),'AI Confidence':0.95,'AI Provider Principal':'Prelectura · gemini-3.5-flash-lite','Fecha Operación Detectada':'2026-08-22','Fuente Fecha Operación':'PROOF_EXTRACTED','Confianza Fecha Operación':'HIGH','Fecha Requiere Revisión':false,'Evidencia Fecha Operación':'Fecha visible extraída del comprobante.'}};const fields=automation.resultFields({ok:false,reason:'TIMEOUT',detail:'Gemini excedió el límite.',processingState:'Revisión manual urgente',resultValidation:'Revisión manual urgente',processingAttempts:2},prior);assert.match(fields['Normalized Analysis JSON'],/prefill/);assert.equal(fields['AI Confidence'],0.95);assert.equal(fields['AI Failure Reason'],'TIMEOUT');assert.match(fields['Último Error de Procesamiento'],/TIMEOUT/);assert.equal(fields['Intentos de Procesamiento'],2);assert.notEqual(fields['Rules Evaluation JSON'],'{}')});
test('background clasifica fallos transitorios para reintento nativo',()=>{for(const code of ['TIMEOUT','RATE_LIMIT','PROVIDER_UNAVAILABLE','EMPTY_OUTPUT','PROCESSING_CAS_CONFLICT','BLOBS_UNAVAILABLE'])assert.equal(background.retryable(code),true);for(const code of ['AI_AUTH_FAILED','RECIPIENT_MISMATCH','LOW_CONFIDENCE'])assert.equal(background.retryable(code),false)});
test('configuración explícita no puede ser sobreescrita por discovery',()=>{const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_shared','_payment_report_automation.js'),'utf8');assert(!/if\(models\[0\]\)configuredAi\.primaryModel=models\[0\]/.test(source));assert.match(source,/if\(!configuredAi\.primaryModel&&models\[0\]\)configuredAi\.primaryModel=models\[0\]/);assert(!/configuredAi\.secondaryEnabled=true/.test(source))});
test('orquestador usa secundario solo como fallback y conserva retry con jitter',()=>{const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_shared','_payment_processing_orchestrator.js'),'utf8');assert(!/secondary-consensus|AI_CONSENSUS|_payment_ai_consensus/.test(source));assert.match(source,/action\.action==='SECONDARY'/);assert.match(source,/retryDelayMs/);assert.match(source,/automaticApprovalEnabled:config\.automaticApprovalEnabled/)});
test('la combinación de fecha usa la menor confianza de ambas lecturas',()=>{const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_shared','_payment_processing_orchestrator.js'),'utf8');assert.match(source,/confidence:Math\.min\(Number\(primaryExtracted\.confidence\).*Number\(evaluated\.normalized\.confidence\)/)});
