'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const cash=require('../netlify/functions/_cash_payment_policy');

(()=>{
 const receivedAt=new Date('2026-07-13T18:00:00.000Z');
 const direct=cash.directAdminCash({ownerId:'recOwner1',adminId:'adminEnzo',amount:100,currency:'USD',receivedAt,receiptReference:'REC-001',notes:'Pago directo en administración'});
 assert.strictEqual(direct.type,'DIRECT_ADMIN');assert.strictEqual(direct.status,'DEFINITIVE_PAYMENT_AUTHORIZED_NOT_EXECUTED');assert.strictEqual(direct.createsPayment,true);assert.strictEqual(direct.reducesBalance,true);assert.strictEqual(direct.createsReceipt,true);assert.strictEqual(direct.recalculatesAccess,true);assert.strictEqual(direct.executed,false);assert.strictEqual(direct.airtableAction,'NONE');assert.strictEqual(direct.mkjAction,'NONE');assert.strictEqual(cash.invariant(direct),true);assert.match(direct.idempotencyKey,/^CASH_DIRECT\|[a-f0-9]{64}$/);
 const directReplay=cash.directAdminCash({ownerId:'recOwner1',adminId:'adminEnzo',amount:100,currency:'USD',receivedAt,receiptReference:'REC-001'});assert.strictEqual(directReplay.idempotencyKey,direct.idempotencyKey);
 const changed=cash.directAdminCash({ownerId:'recOwner1',adminId:'adminEnzo',amount:101,currency:'USD',receivedAt,receiptReference:'REC-001'});assert.notStrictEqual(changed.idempotencyKey,direct.idempotencyKey);
 assert.throws(()=>cash.directAdminCash({ownerId:'recOwner1',amount:100,currency:'USD',receiptReference:'REC-001'}),error=>error.code==='CASH_LINK_MISSING');
 assert.throws(()=>cash.directAdminCash({ownerId:'recOwner1',adminId:'admin',amount:0,currency:'USD',receiptReference:'REC-001'}),error=>error.code==='CASH_AMOUNT_INVALID');
 assert.throws(()=>cash.directAdminCash({ownerId:'recOwner1',adminId:'admin',amount:100,currency:'EUR',receiptReference:'REC-001'}),error=>error.code==='CASH_CURRENCY_INVALID');
 assert.throws(()=>cash.directAdminCash({ownerId:'recOwner1',adminId:'admin',amount:100,currency:'USD'}),error=>error.code==='CASH_RECEIPT_REFERENCE_REQUIRED');
 const pending=cash.securityPendingCash({ownerId:'recOwner1',receivedBy:'guardGustavo',amount:250,currency:'VES',receivedAt,location:'Vigilancia',evidenceReference:'CONST-001'});
 assert.strictEqual(pending.type,'SECURITY_PENDING');assert.strictEqual(pending.status,'PENDING_ADMIN_CONFIRMATION');assert.strictEqual(pending.createsPayment,false);assert.strictEqual(pending.reducesBalance,false);assert.strictEqual(pending.createsReceipt,false);assert.strictEqual(pending.recalculatesAccess,false);assert.strictEqual(pending.paymentAction,'NONE');assert.strictEqual(pending.balanceAction,'NONE');assert.strictEqual(pending.accessAction,'NONE');assert.strictEqual(pending.executed,false);assert.strictEqual(pending.requiresAdminConfirmation,true);assert.strictEqual(cash.invariant(pending),true);assert.match(pending.pendingId,/^CASH_PENDING\|[a-f0-9]{64}$/);
 assert.throws(()=>cash.securityPendingCash({ownerId:'recOwner1',receivedBy:'guard',amount:10,currency:'USD'}),error=>error.code==='CASH_EVIDENCE_REQUIRED');
 const confirmed=cash.confirmSecurityCash({pending,adminId:'adminEnzo',confirmedAt:new Date('2026-07-13T19:00:00.000Z'),receiptReference:'REC-002'});
 assert.strictEqual(confirmed.type,'DIRECT_ADMIN');assert.strictEqual(confirmed.sourceType,'SECURITY_PENDING_CONFIRMED');assert.strictEqual(confirmed.sourcePendingId,pending.pendingId);assert.strictEqual(confirmed.createsPayment,true);assert.strictEqual(confirmed.reducesBalance,true);assert.strictEqual(confirmed.createsReceipt,true);assert.strictEqual(confirmed.executed,false);assert.strictEqual(cash.invariant(confirmed),true);
 assert.throws(()=>cash.confirmSecurityCash({pending:{type:'SECURITY_PENDING',status:'DONE'},adminId:'admin',receiptReference:'x'}),error=>error.code==='CASH_PENDING_INVALID');
 const contingency=cash.contingencyAccess({ownerId:'recOwner1',adminId:'adminEnzo',reason:'Falla eléctrica y necesidad de entrada urgente',durationHours:2,now:receivedAt});
 assert.strictEqual(contingency.type,'CONTINGENCY');assert.strictEqual(contingency.status,'CONTINGENCY_AUTHORIZED_NOT_EXECUTED');assert.strictEqual(contingency.createsPayment,false);assert.strictEqual(contingency.reducesBalance,false);assert.strictEqual(contingency.paymentAction,'NONE');assert.strictEqual(contingency.balanceAction,'NONE');assert.strictEqual(contingency.createsReceipt,false);assert.strictEqual(contingency.accessAction,'TEMPORARY_ACCESS_CONTINGENCY_REQUEST');assert.strictEqual(contingency.executed,false);assert.strictEqual(contingency.auditRequired,true);assert.strictEqual(contingency.expiresAt,'2026-07-13T20:00:00.000Z');assert.strictEqual(cash.invariant(contingency),true);
 assert.throws(()=>cash.contingencyAccess({ownerId:'recOwner1',adminId:'admin',reason:'corto',durationHours:1,now:receivedAt}),error=>error.code==='CONTINGENCY_REASON_REQUIRED');
 assert.throws(()=>cash.contingencyAccess({ownerId:'recOwner1',adminId:'admin',reason:'Motivo suficientemente largo',expiresAt:'2026-07-15T18:00:00.000Z',now:receivedAt}),error=>error.code==='CONTINGENCY_DURATION_INVALID');
 assert.strictEqual(cash.classifyCashRequest('security_pending',{ownerId:'recOwner1',receivedBy:'guard',amount:1,currency:'USD',evidenceReference:'e'}).type,'SECURITY_PENDING');
 assert.throws(()=>cash.classifyCashRequest('unknown',{}),error=>error.code==='CASH_TYPE_INVALID');
 const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_cash_payment_policy.js'),'utf8');assert(!/airtableCreateRecord|airtablePatchRecord|syncOwnerAccess|mkjSetMemberStatus|sendMail/.test(source));
 console.log('CASH_PAYMENT_POLICY_OK');
})();
