'use strict';
const assert=require('assert');
const {buildPlan}=require('../netlify/functions/_monthly_close_core_v4');
const owner={id:'recOwner000000001',fields:{Casa:1,Propietario:'Prueba',Alicuota:1,'Deuda Anterior':0,'Deuda Anterior USD':0,'Deuda Anterior Bs Ref':0,'Deuda Restante':0}};
const base={id:'recPayment0000001',fields:{'Propietario que Paga':[owner.id],'Monto Pagado':10,'Equivalente USD Aplicado':10,'Fecha de Pago':'2026-07-01'}};
const plan=payment=>buildPlan({owners:[owner],expenses:[],payments:[payment],month:'2026-07'});
const legacy=plan(base);
const explicitLegacy=plan({...base,fields:{...base.fields,'Forma de Pago':'LEGACY'}});
const explicitBs=plan({...base,fields:{...base.fields,'Forma de Pago':'Bs BCV'}});
assert.strictEqual(legacy.sourceHash,explicitLegacy.sourceHash,'Un pago histórico sin moneda debe representarse como LEGACY en la huella.');
assert.notStrictEqual(legacy.sourceHash,explicitBs.sourceHash,'Un pago histórico sin moneda no debe serializarse como Bs BCV.');
console.log('MONTHLY_CLOSE_LEGACY_HASH_OK');
