'use strict';
const assert=require('assert');
const {buildPlan}=require('../netlify/functions/_monthly_close_core_v4');
const owner={id:'recOwner000000001',fields:{Casa:1,Propietario:'Prueba',Alicuota:1,'Deuda Anterior':0,'Deuda Anterior USD':10,'Deuda Anterior Bs Ref':5,'Deuda Restante':15}};
const base={id:'recPayment0000001',fields:{'Propietario que Paga':[owner.id],'Monto Pagado':8,'Equivalente USD Aplicado':8,'Fecha de Pago':'2026-07-01'}};
const plan=payment=>buildPlan({owners:[owner],expenses:[],payments:[payment],month:'2026-07'});
const legacy=plan(base);
const explicitLegacy=plan({...base,fields:{...base.fields,'Forma de Pago':'LEGACY'}});
const explicitBs=plan({...base,fields:{...base.fields,'Forma de Pago':'Bs BCV'}});
const repeated=plan(JSON.parse(JSON.stringify(base)));
assert.strictEqual(legacy.sourceHash,explicitLegacy.sourceHash,'Un pago histórico sin moneda debe representarse como LEGACY en la huella.');
assert.strictEqual(legacy.planHash,explicitLegacy.planHash,'La forma LEGACY implícita y explícita deben producir el mismo plan.');
assert.strictEqual(legacy.planHash,repeated.planHash,'La huella debe ser determinista entre ejecuciones equivalentes.');
assert.notStrictEqual(legacy.sourceHash,explicitBs.sourceHash,'LEGACY no es equivalente a Bs BCV: puede aplicar primero a Bs y luego a USD.');
assert.notStrictEqual(legacy.planHash,explicitBs.planHash,'Cambiar un pago histórico a Bs BCV altera la semántica y debe invalidar la simulación.');
assert.strictEqual(legacy.ownerUpdates[0].target.deudaAnterior,explicitLegacy.ownerUpdates[0].target.deudaAnterior);
console.log('MONTHLY_CLOSE_LEGACY_HASH_OK');
