'use strict';
const fs=require('fs');const assert=require('assert');
const ui=fs.readFileSync('owner-payment-report-v3.js','utf8');
const css=fs.readFileSync('owner-payment-report-v3.css','utf8');
const edge=fs.readFileSync('netlify/edge-functions/owner-mobile-assets.js','utf8');
const signature=fs.readFileSync('netlify/edge-functions/owner-signature.js','utf8');
const server=fs.readFileSync('netlify/functions/public-report-payment.js','utf8');

for(const marker of ['¿Cómo realizaste el pago?','Pago digital','Efectivo','Sube tu comprobante','Tomar foto / Elegir comprobante','Pago detectado','Confirmar pago','Necesitamos un dato adicional','¿Algo está incorrecto? Editar','Completar manualmente','Binance'])assert(ui.includes(marker),`Falta ${marker}`);
assert(!/<input[^>]*name="payChannel"[^>]*\schecked(?:\s|>)/.test(ui),'La primera pantalla no debe preseleccionar un canal.');
assert(/id="vla-pay-proof-section"[^>]*hidden/.test(ui),'La carga debe aparecer solo después de elegir pago digital.');
assert(/id="vla-pay-details"[^>]*hidden/.test(ui),'El formulario no puede aparecer completo inicialmente.');
assert(/id="payTransactionStatus" type="hidden"/.test(ui),'El estado técnico debe ser invisible para el propietario.');
assert(!ui.includes('Estado visible'),'El propietario no debe elegir estados técnicos.');
assert(ui.includes('FALLBACK_DATE_METHODS')&&ui.includes('transactionDateSource'),'Debe aceptar y transmitir la política de fecha de Zelle/Binance.');
assert(ui.includes("cash?(currency==='BS'?'Bs BCV':currency==='USD'?'USD':'')"),'El efectivo debe asignar la cuenta desde su moneda sin pedir un campo oculto.');
assert(!/function cashMissing\(\)\{[^}]*missing\.push\('mode'\)/.test(ui),'El flujo de efectivo no puede exigir una cuenta oculta.');
assert(ui.includes("if(!selectedFile)return['proof']"),'Antes del comprobante solo debe pedirse el comprobante.');
assert(ui.includes("openReport=openSmartReport"),'Debe sustituir el flujo heredado.');
assert(ui.includes("addEventListener('submit',submitSmartReport)"),'Debe existir un único manejador de envío.');
assert(ui.includes('/api/vla/payment-proof-prefill')&&ui.includes('/api/vla/report-payment'),'Debe conservar prelectura y validación backend.');
assert(ui.includes('submissionId')&&ui.includes('readAsDataURL'),'Debe conservar idempotencia y carga segura.');
assert(!signature.includes('form.onsubmit')&&!signature.includes('/.netlify/functions/public-report-payment'),'Ningún parche heredado puede duplicar el envío.');
assert(!/recargo/i.test(ui+css),'El portal público no debe mencionar el recargo.');
assert(css.includes('.vla-pay-two{display:grid')&&css.includes('font-size:16px'),'Debe seguir siendo móvil y evitar zoom en iPhone.');
assert(edge.includes('progressive-v6'),'Falta el marcador del flujo progresivo.');
for(const asset of ['owner-payment-report-v3.css','payment-report-intelligence.js','owner-payment-report-v3.js'])assert(edge.includes(asset),`Falta inyección de ${asset}`);
assert(server.includes('DATE_FALLBACK_METHODS')&&server.includes('REPORT_TIMESTAMP_FALLBACK'),'El servidor debe controlar el fallback de fecha.');
assert(server.includes("paymentChannel==='DIGITAL'?decodeAttachment(body.attachment):null"),'El comprobante es obligatorio solo para digital.');
assert(server.includes("'Archivo Obligatorio':paymentChannel==='DIGITAL'")&&server.includes('reserveIdentity'),'Debe conservar comprobante condicional y deduplicación.');
assert(!server.includes('ACCEPTED_TRANSACTION_STATUSES'),'El cliente no decide si una transacción está completada.');
console.log('owner-payment-report-progressive-v6: OK');
