'use strict';
const assert=require('assert');
const arbiter=require('../netlify/functions/_payment_deterministic_arbiter');

const now=new Date('2026-07-13T16:30:00.000Z');
function account(overrides={}){return{id:'recAccount1',fields:{Activo:true,Método:'Zelle',Moneda:'USD','Titular Autorizado':'ENZO PANARITO','Correo Normalizado':'enzopanarito@gmail.com','Versión de Configuración':1,...overrides}}}
function base(overrides={}){return{report:{id:'recReport1',fields:{'Forma de Pago Reportada':'USD','Estado Acceso al Reportar':'Limitado','Archivo Obligatorio':true}},owner:{id:'recOwner1',fields:{'Estado Acceso Portón':'Limitado'}},attachment:{valid:true,sha256:'a'.repeat(64)},analysis:{method:'ZELLE',bank_or_platform:'Zelle',amount:85,currency:'USD',transaction_date:'2026-07-13',transaction_time:'12:00:00',reference:'ABC123',transaction_status:'COMPLETED',recipient_name:'ENZO PANARITO',recipient_phone:null,recipient_email:'enzopanarito@gmail.com',recipient_account_visible:null,memo:null,confidence:0.98,critical_fields_visible:true,warnings:[],possible_visual_modification:false},snapshot:{schemaVersion:2,balanceEngineVersion:5,cacheValid:true,automaticEligibility:true,requiredUsdAccount:85,requiredBsAccount:0,paymentsAfterCutoff:[]},snapshotValidation:{ok:true},duplicate:{isDuplicate:false,possibleDuplicate:false,type:'Sin coincidencia'},authorizedAccounts:[account()],config:{minimumConfidence:0.85},now,...overrides}}
function assertNoAction(result){assert.strictEqual(result.requiresAdminDecision,true);assert.strictEqual(result.automaticApproval,false);assert.strictEqual(result.paymentAction,'NONE');assert.strictEqual(result.accessAction,'NONE');assert.strictEqual(result.canCreatePayment,false);assert.strictEqual(result.canEnableAccess,false)}

(()=>{
 const good=arbiter.evaluatePaymentReport(base());assert.strictEqual(good.processingState,'Coincide preliminarmente');assert.strictEqual(good.resultValidation,'Coincide preliminarmente');assert.strictEqual(good.preliminaryMatch,true);assertNoAction(good);
 const missing=arbiter.evaluatePaymentReport(base({attachment:{valid:false}}));assert.strictEqual(missing.resultValidation,'Archivo ilegible');assertNoAction(missing);
 const duplicate=arbiter.evaluatePaymentReport(base({duplicate:{isDuplicate:true,possibleDuplicate:true,type:'Hash exacto'}}));assert.strictEqual(duplicate.processingState,'Duplicado detectado');assert.strictEqual(duplicate.resultValidation,'Duplicado');assertNoAction(duplicate);
 const low=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,confidence:0.2}}));assert.strictEqual(low.resultValidation,'Baja confianza');assertNoAction(low);
 const pending=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,transaction_status:'PENDING'}}));assert.strictEqual(pending.resultValidation,'Operación pendiente');assertNoAction(pending);
 const failed=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,transaction_status:'FAILED'}}));assert.strictEqual(failed.resultValidation,'Operación fallida');assertNoAction(failed);
 const badCurrency=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,currency:'VES'}}));assert.strictEqual(badCurrency.resultValidation,'Moneda inconsistente');assertNoAction(badCurrency);
 const noRecipient=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,recipient_name:null,recipient_email:null}}));assert.strictEqual(noRecipient.resultValidation,'Receptor no visible');assertNoAction(noRecipient);
 const wrongRecipient=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,recipient_name:'OTRA PERSONA',recipient_email:'other@example.com'}}));assert.strictEqual(wrongRecipient.resultValidation,'Receptor incorrecto');assertNoAction(wrongRecipient);
 const stale=arbiter.evaluatePaymentReport(base({snapshot:{...base().snapshot,cacheValid:false},snapshotValidation:{ok:false}}));assert.strictEqual(stale.processingState,'Revisión manual urgente');assertNoAction(stale);
 const later=arbiter.evaluatePaymentReport(base({snapshot:{...base().snapshot,paymentsAfterCutoff:['recLater']}}));assert.strictEqual(later.processingState,'Revisión manual urgente');assertNoAction(later);
 const insufficient=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,amount:84.98}}));assert.strictEqual(insufficient.resultValidation,'Monto insuficiente');assertNoAction(insufficient);
 const partial=arbiter.evaluatePaymentReport(base({duplicate:{isDuplicate:false,possibleDuplicate:true,type:'Referencia parcial'}}));assert.strictEqual(partial.processingState,'Pendiente de administrador');assertNoAction(partial);
 const future=arbiter.evaluatePaymentReport(base({analysis:{...base().analysis,transaction_date:'2026-07-15'}}));assert.strictEqual(future.resultValidation,'Fecha inválida');assertNoAction(future);
 const expiredAccount=arbiter.evaluatePaymentReport(base({authorizedAccounts:[account({'Fecha de Vencimiento':'2026-07-12'})]}));assert.strictEqual(expiredAccount.resultValidation,'Receptor incorrecto');assertNoAction(expiredAccount);
 const bs=arbiter.evaluatePaymentReport(base({report:{id:'r',fields:{'Forma de Pago Reportada':'Bs BCV','Estado Acceso al Reportar':'Limitado','Archivo Obligatorio':true}},analysis:{...base().analysis,method:'MOBILE_PAYMENT_VE',currency:'VES',amount:5000,recipient_name:null,recipient_email:null,recipient_phone:'04140554700'},snapshot:{...base().snapshot,requiredUsdAccount:0,requiredBsAccount:5000},authorizedAccounts:[account({Método:'Pago móvil Venezuela',Moneda:'VES','Titular Autorizado':'','Correo Normalizado':'','Teléfono Normalizado':'04140554700'})]}));assert.strictEqual(bs.preliminaryMatch,true);assertNoAction(bs);
 console.log('PAYMENT_DETERMINISTIC_ARBITER_OK');
})();
