'use strict';

const assert=require('assert');
const fs=require('fs');
const path=require('path');
const machine=require('../netlify/functions/_payment_decision_state_machine');
const cash=require('../netlify/functions/_cash_payment_policy');

function report(overrides={}){return{id:'recReport1',fields:{'Propietario que Reporta':['recOwner1'],Estado:'Pendiente','Pago Definitivo Creado':false,'Forma de Pago Reportada':'USD','Equivalente USD Reportado':85,'Monto Reportado':85,Referencia:'REF-001','Habilitación Provisional Aplicada':false,'MKJ Operation ID':'',...overrides}}}
function owner(overrides={}){return{id:'recOwner1',fields:{'Reporte Habilitante Actual':[],'Tipo de Habilitación':'',...overrides}}}
function decision(overrides={}){return{preliminaryMatch:true,automaticApproval:false,paymentAction:'NONE',accessAction:'NONE',canCreatePayment:false,canEnableAccess:false,requiresAdminDecision:true,processingState:'Coincide preliminarmente',resultValidation:'Coincide preliminarmente',...overrides}}
function snapshot(overrides={}){return{schemaVersion:2,balanceEngineVersion:5,cacheValid:true,automaticEligibility:true,paymentsAfterCutoff:[],snapshotId:'BALANCE_SNAPSHOT_V2|'+'a'.repeat(64),...overrides}}
function assertNoExecution(value){assert.strictEqual(value.executed,false);assert.strictEqual(value.airtableAction,'NONE');assert.strictEqual(value.mkjAction,'NONE');assert.strictEqual(value.emailAction,'NONE')}

(()=>{
 const now=new Date('2026-07-13T19:00:00.000Z');
 const approved=machine.authorizeReportApproval({report:report(),owner:owner(),adminId:'adminEnzo',decision:decision(),snapshot:snapshot(),snapshotValidation:{ok:true},now});
 assert.strictEqual(approved.state,'PAYMENT_CREATE_PENDING');assert.strictEqual(approved.source,'REPORT_APPROVAL');assert.deepStrictEqual(machine.nextActions(approved),['CREATE_PAYMENT_ONCE']);assert.strictEqual(approved.paymentPayload.amountUsd,85);assert.strictEqual(approved.paymentPayload.mode,'USD');assertNoExecution(approved);
 const otherAdmin=machine.authorizeReportApproval({report:report(),owner:owner(),adminId:'adminFernando',decision:decision(),snapshot:snapshot(),snapshotValidation:{ok:true},now});assert.strictEqual(otherAdmin.decisionId,approved.decisionId,'La clave del pago no puede depender del administrador.');
 assert.throws(()=>machine.authorizeReportApproval({report:report(),owner:owner(),adminId:'admin',decision:decision({canEnableAccess:true}),snapshot:snapshot(),snapshotValidation:{ok:true},now}),error=>error.code==='DECISION_INVARIANT_FAILED');
 assert.throws(()=>machine.authorizeReportApproval({report:report(),owner:owner(),adminId:'admin',decision:decision(),snapshot:snapshot(),snapshotValidation:{ok:false},now}),error=>error.code==='DECISION_SNAPSHOT_CHANGED');
 assert.throws(()=>machine.authorizeReportApproval({report:report({Estado:'Confirmado'}),owner:owner(),adminId:'admin',decision:decision(),snapshot:snapshot(),snapshotValidation:{ok:true},now}),error=>error.code==='DECISION_PAYMENT_ALREADY_CREATED');

 const paid=machine.recordPaymentCreated(approved,{paymentId:'recPayment1',at:new Date('2026-07-13T19:01:00.000Z')});assert.strictEqual(paid.state,'RECEIPT_RECORD_PENDING');assert.strictEqual(paid.paymentId,'recPayment1');assert.deepStrictEqual(machine.nextActions(paid),['CREATE_RECEIPT_RECORD_ONCE']);assert(!machine.nextActions(paid).includes('CREATE_PAYMENT_ONCE'));assertNoExecution(paid);
 const paidReplay=machine.recordPaymentCreated(paid,{paymentId:'recPayment1'});assert.deepStrictEqual(paidReplay,paid);assert.throws(()=>machine.recordPaymentCreated(paid,{paymentId:'recPayment2'}),error=>error.code==='PAYMENT_ALREADY_BOUND');
 const receiptFailed=machine.recordReceiptOutcome(paid,{recorded:false,error:'PDF temporalmente no disponible',at:new Date('2026-07-13T19:02:00.000Z')});assert.strictEqual(receiptFailed.paymentId,'recPayment1');assert.strictEqual(receiptFailed.state,'RECEIPT_RECORD_PENDING');assert.deepStrictEqual(machine.nextActions(receiptFailed),['CREATE_RECEIPT_RECORD_ONCE']);assert(!machine.nextActions(receiptFailed).includes('CREATE_PAYMENT_ONCE'));
 const receiptRecorded=machine.recordReceiptOutcome(receiptFailed,{receiptId:'recReceipt1',recorded:true,emailSent:false,error:'Correo temporalmente no disponible',at:new Date('2026-07-13T19:03:00.000Z')});assert.strictEqual(receiptRecorded.receiptRecordStatus,'RECORDED');assert.strictEqual(receiptRecorded.receiptDeliveryStatus,'FAILED');assert.strictEqual(receiptRecorded.state,'ACCESS_RECALC_PENDING');assert.deepStrictEqual(machine.nextActions(receiptRecorded),['DELIVER_RECEIPT_ONLY','RECALCULATE_ACCESS_ONLY']);assert(!machine.nextActions(receiptRecorded).includes('CREATE_PAYMENT_ONCE'));
 const receiptReplay=machine.recordReceiptOutcome(receiptRecorded,{receiptId:'recReceipt1',recorded:true,emailSent:false});assert.deepStrictEqual(receiptReplay,receiptRecorded);assert.throws(()=>machine.recordReceiptOutcome(receiptRecorded,{receiptId:'recReceipt2',recorded:true}),error=>error.code==='RECEIPT_ALREADY_BOUND');
 const accessFailed=machine.recordAccessOutcome(receiptRecorded,{success:false,error:'MKJ temporalmente no disponible',at:new Date('2026-07-13T19:04:00.000Z')});assert.strictEqual(accessFailed.accessRecalculationStatus,'FAILED');assert.strictEqual(accessFailed.paymentId,'recPayment1');assert.deepStrictEqual(machine.nextActions(accessFailed),['DELIVER_RECEIPT_ONLY','RECALCULATE_ACCESS_ONLY']);
 const accessDone=machine.recordAccessOutcome(accessFailed,{success:true,status:'Habilitado',at:new Date('2026-07-13T19:05:00.000Z')});assert.strictEqual(accessDone.state,'COMPLETED_RECEIPT_DELIVERY_PENDING');assert.strictEqual(accessDone.accessRecalculationStatus,'DONE');assert.deepStrictEqual(machine.nextActions(accessDone),['DELIVER_RECEIPT_ONLY']);
 const accessReplay=machine.recordAccessOutcome(accessDone,{success:true,status:'Habilitado'});assert.deepStrictEqual(accessReplay,accessDone);
 const complete=machine.recordReceiptDelivery(accessDone,{sent:true,at:new Date('2026-07-13T19:06:00.000Z')});assert.strictEqual(complete.state,'COMPLETED');assert.strictEqual(complete.receiptDeliveryStatus,'SENT');assert.deepStrictEqual(machine.nextActions(complete),[]);assertNoExecution(complete);
 const deliveryReplay=machine.recordReceiptDelivery(complete,{sent:true});assert.deepStrictEqual(deliveryReplay,complete);

 const paid2=machine.recordPaymentCreated(machine.authorizeReportApproval({report:report({Referencia:'REF-002'}),owner:owner(),adminId:'admin',decision:decision(),snapshot:snapshot({snapshotId:'snap2'}),snapshotValidation:{ok:true},now}),{paymentId:'recPayment2'});
 const receiptSent=machine.recordReceiptOutcome(paid2,{receiptId:'recReceipt2',recorded:true,emailSent:true});const complete2=machine.recordAccessOutcome(receiptSent,{success:true,status:'Limitado'});assert.strictEqual(complete2.state,'COMPLETED');assert.deepStrictEqual(machine.nextActions(complete2),[]);
 assert.throws(()=>machine.recordAccessOutcome(paid2,{success:true}),error=>error.code==='ACCESS_RECEIPT_REQUIRED');

 const cashUsd=cash.directAdminCash({ownerId:'recOwner1',adminId:'adminEnzo',amount:100,currency:'USD',receivedAt:now,receiptReference:'CASH-USD-1'}),cashMachine=machine.authorizeCashApproval({cashProposal:cashUsd,now});assert.strictEqual(cashMachine.source,'CASH_DIRECT');assert.strictEqual(cashMachine.paymentPayload.amountUsd,100);assert.strictEqual(cashMachine.paymentPayload.mode,'USD');assert.deepStrictEqual(machine.nextActions(cashMachine),['CREATE_PAYMENT_ONCE']);
 const cashUsdOtherAdmin={...cashUsd,adminId:'adminFernando'};assert.strictEqual(machine.authorizeCashApproval({cashProposal:cashUsdOtherAdmin,now}).decisionId,cashMachine.decisionId);
 const cashBs=cash.directAdminCash({ownerId:'recOwner1',adminId:'adminEnzo',amount:5000,currency:'VES',receivedAt:now,receiptReference:'CASH-BS-1'}),cashBsMachine=machine.authorizeCashApproval({cashProposal:cashBs,bcvRate:50,now});assert.strictEqual(cashBsMachine.paymentPayload.mode,'Bs BCV');assert.strictEqual(cashBsMachine.paymentPayload.amountBs,5000);assert.strictEqual(cashBsMachine.paymentPayload.amountUsd,100);assert.strictEqual(cashBsMachine.paymentPayload.rate,50);
 assert.throws(()=>machine.authorizeCashApproval({cashProposal:cashBs,now}),error=>['PAYMENT_AMOUNT_INVALID','PAYMENT_BS_INVALID'].includes(error.code));
 const security=cash.securityPendingCash({ownerId:'recOwner1',receivedBy:'guard',amount:100,currency:'USD',evidenceReference:'EVID-1'});assert.throws(()=>machine.authorizeCashApproval({cashProposal:security,now}),error=>error.code==='CASH_APPROVAL_INVALID');

 const rejected=machine.authorizeRejection({report:report(),owner:owner(),adminId:'adminEnzo',reason:'Comprobante no corresponde al receptor autorizado',now});assert.strictEqual(rejected.state,'REJECTED');assert.strictEqual(rejected.paymentAction,'NONE');assert.strictEqual(rejected.receiptAction,'NONE');assert.strictEqual(rejected.accessAction,'NONE');assert.deepStrictEqual(machine.nextActions(rejected),[]);assertNoExecution(rejected);
 const rejectedOtherAdmin=machine.authorizeRejection({report:report(),owner:owner(),adminId:'adminFernando',reason:'Comprobante no corresponde al receptor autorizado',now});assert.strictEqual(rejectedOtherAdmin.decisionId,rejected.decisionId);
 const provisionalReport=report({'Habilitación Provisional Aplicada':true,'MKJ Operation ID':'PROVISIONAL|abc'}),provisionalOwner=owner({'Reporte Habilitante Actual':['recReport1'],'Tipo de Habilitación':'Provisional por comprobante'}),reversal=machine.authorizeRejection({report:provisionalReport,owner:provisionalOwner,adminId:'adminEnzo',reason:'El comprobante fue rechazado después de revisión',now});assert.strictEqual(reversal.state,'REVERSAL_PENDING');assert.deepStrictEqual(machine.nextActions(reversal),['RELIMIT_EXACT_REJECTED_REPORT']);
 const exact=machine.evaluateRejectionReversal(reversal,{owner:provisionalOwner,report:provisionalReport});assert.strictEqual(exact.requestedAction,'RELIMIT_EXACT_REJECTED_REPORT');assert.strictEqual(exact.operationId,'PROVISIONAL|abc');assert.strictEqual(exact.executed,false);
 const stale=machine.evaluateRejectionReversal(reversal,{owner:owner({'Reporte Habilitante Actual':['recNew']}),report:provisionalReport});assert.strictEqual(stale.requestedAction,'NONE');assert.strictEqual(stale.reason,'STALE_REPORT_REPLACED');
 const paidReport=machine.evaluateRejectionReversal(reversal,{owner:provisionalOwner,report:report({'Habilitación Provisional Aplicada':true,'MKJ Operation ID':'PROVISIONAL|abc','Pago Definitivo Creado':true,Estado:'Confirmado'})});assert.strictEqual(paidReport.reason,'DEFINITIVE_PAYMENT_CREATED');
 const replaced=machine.evaluateRejectionReversal(reversal,{owner:provisionalOwner,report:report({'Habilitación Provisional Aplicada':true,'MKJ Operation ID':'PROVISIONAL|new'})});assert.strictEqual(replaced.reason,'OPERATION_REPLACED');
 const reversalFailed=machine.recordReversalOutcome(reversal,{success:false,error:'MKJ temporalmente no disponible'});assert.strictEqual(reversalFailed.state,'REVERSAL_PENDING');assert.deepStrictEqual(machine.nextActions(reversalFailed),['RELIMIT_EXACT_REJECTED_REPORT']);const reversed=machine.recordReversalOutcome(reversalFailed,{success:true,status:'Limitado'});assert.strictEqual(reversed.state,'REVERSED');assert.deepStrictEqual(machine.nextActions(reversed),[]);assert.deepStrictEqual(machine.recordReversalOutcome(reversed,{success:true,status:'Limitado'}),reversed);
 assert.throws(()=>machine.authorizeRejection({report:report({'Pago Definitivo Creado':true}),owner:owner(),adminId:'admin',reason:'Motivo suficientemente largo'}),error=>error.code==='REJECTION_PAYMENT_EXISTS');
 assert.throws(()=>machine.authorizeRejection({report:report(),owner:owner(),adminId:'admin',reason:'corto'}),error=>error.code==='REJECTION_REASON_REQUIRED');

 const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_payment_decision_state_machine.js'),'utf8');assert(!/airtableCreateRecord|airtablePatchRecord|syncOwnerAccess|mkjSetMemberStatus|sendMail|createAndSendReceipt/.test(source));
 console.log('PAYMENT_DECISION_STATE_MACHINE_OK');
})();
