'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const processingModule=require('../netlify/functions/_payment_processing_store');
const arbiter=require('../netlify/functions/_payment_deterministic_arbiter');
const orchestratorModule=require('../netlify/functions/_payment_processing_orchestrator');

function modules(){
 const proofCore={decodeProofInput(input){const sha=(input&&input.sha)||'a'.repeat(64);return{filename:'proof.png',content:Buffer.from(input?.content||'proof'),contentType:'image/png',size:5,sha256:sha,quality:{acceptable:true}}},buildIdempotencyKey(reportId,sha,prompt){return`${reportId}|${sha}|${prompt}`}};
 const duplicateCore={canonicalFingerprint(a){return[a.method,a.reference,a.currency,a.amount].join('|')},fingerprintHash(v){return require('crypto').createHash('sha256').update(v).digest('hex')},findDuplicateMatches(input,data){const exact=(data.reports||[]).find(r=>r.sha===input.exactSha);if(exact)return{isDuplicate:true,possibleDuplicate:true,type:'Hash exacto',matches:[exact]};const partial=(data.history||[]).find(r=>r.reference===input.reference);if(partial)return{isDuplicate:false,possibleDuplicate:true,type:'Referencia parcial',matches:[partial]};return{isDuplicate:false,possibleDuplicate:false,type:'Sin coincidencia',matches:[]}}};
 const snapshotCore={buildAccessSnapshot(){return{schemaVersion:2,balanceEngineVersion:5,cacheValid:true,automaticEligibility:true,requiredUsdAccount:85,requiredBsAccount:0,paymentsAfterCutoff:[],snapshotId:'snap1'}},validateSnapshotStillCurrent(){return{ok:true}}};
 const aiContract={safeConfig(c={}){return{aiEnabled:c.aiEnabled===true,primaryModel:c.primaryModel||'',secondaryEnabled:c.secondaryEnabled===true,secondaryModel:c.secondaryModel||'',maximumPrimaryRetries:Number(c.maximumPrimaryRetries||0),minimumConfidence:c.minimumConfidence??0.85,promptVersion:c.promptVersion||'PROMPT_V2'}},nextAiAction({config,primaryAttempts,secondaryAttempts,lastFailure}){if(!config.aiEnabled||!config.primaryModel)return{action:'MANUAL_URGENT',reason:'AI_NOT_CONFIGURED'};if(primaryAttempts<1)return{action:'PRIMARY'};if(primaryAttempts<1+config.maximumPrimaryRetries&&['TIMEOUT','RATE_LIMIT','PROVIDER_UNAVAILABLE','TEMPORARY_ERROR'].includes(lastFailure))return{action:'PRIMARY_RETRY'};if(config.secondaryEnabled&&config.secondaryModel&&config.secondaryModel!==config.primaryModel&&secondaryAttempts<1)return{action:'SECONDARY'};return{action:'MANUAL_URGENT',reason:lastFailure||'AI_ATTEMPTS_EXHAUSTED'}},evaluateRawOutput(raw,{minimumConfidence}){try{const value=JSON.parse(raw);if(value.confidence<minimumConfidence)return{ok:false,reason:'LOW_CONFIDENCE',raw};return{ok:true,raw,normalized:value}}catch(_){return{ok:false,reason:'INVALID_JSON',raw}}},analysisAudit({model,secondary,result}){return{model,secondary,ok:result.ok,failureReason:result.ok?'':result.reason}}};
 return{proofCore,duplicateCore,snapshotCore,aiContract,arbiter};
}
function owner(){return{id:'recOwner1',fields:{'Estado Acceso Portón':'Limitado'}}}
function report(id='recReport1'){return{id,fields:{'Forma de Pago Reportada':'USD','Estado Acceso al Reportar':'Limitado','Archivo Obligatorio':true}}}
function account(){return{id:'recAcc',fields:{Activo:true,Método:'Zelle',Moneda:'USD','Titular Autorizado':'ENZO PANARITO','Correo Normalizado':'enzopanarito@gmail.com'}}}
function analysis(overrides={}){return{method:'ZELLE',bank_or_platform:'Zelle',amount:85,currency:'USD',transaction_date:'2026-07-13',transaction_time:'12:00:00',reference:'REF1',transaction_status:'COMPLETED',recipient_name:'ENZO PANARITO',recipient_phone:null,recipient_email:'enzopanarito@gmail.com',recipient_account_visible:null,memo:null,confidence:0.98,critical_fields_visible:true,warnings:[],possible_visual_modification:false,...overrides}}
function env(){return{VLA_DATA_ENVIRONMENT:'test',AIRTABLE_BASE_ID:'appTEST0000000001'}}
function setup(runner){let clock=Date.parse('2026-07-13T16:30:00.000Z');const memory=processingModule.createMemoryStore(),processingStore=processingModule.createProcessingStore({storeFactory:async()=>memory,now:()=>clock,randomBytes:size=>Buffer.alloc(size,1),leaseMs:30000});let proofWrites=0;const proofStore={async put({attachmentSha}){proofWrites+=1;return{key:`proof/${attachmentSha}`,created:proofWrites===1}}};const orchestrator=orchestratorModule.createOrchestrator({modules:modules(),processingStore,proofStore,analysisRunner:runner,now:()=>new Date(clock)});return{orchestrator,processingStore,get proofWrites(){return proofWrites},advance(ms){clock+=ms}}}
function input(id='recReport1',extra={}){return{report:report(id),owner:owner(),attachment:{sha:'a'.repeat(64),content:'proof'},authorizedAccounts:[account()],payments:[],expenses:[],officialRecords:[],bcvRate:50,config:{aiEnabled:true,primaryModel:'primary',secondaryEnabled:false,minimumConfidence:0.85,promptVersion:'PROMPT_V2'},...extra}}
function assertNoAction(r){assert.strictEqual(r.paymentAction,'NONE');assert.strictEqual(r.accessAction,'NONE');assert.strictEqual(r.canCreatePayment,false);assert.strictEqual(r.canEnableAccess,false);assert.strictEqual(r.automaticApproval,false)}

(async()=>{
 let calls=0;const disabled=setup(async()=>{calls+=1;return JSON.stringify(analysis())});const disabledResult=await disabled.orchestrator.run(input('recDisabled',{config:{aiEnabled:false,promptVersion:'PROMPT_V2'}}),env());assert.strictEqual(calls,0);assert.strictEqual(disabledResult.processingState,'Revisión manual urgente');assert.strictEqual(disabledResult.analysis.failureReason,'AI_NOT_CONFIGURED');assertNoAction(disabledResult);
 calls=0;const valid=setup(async()=>{calls+=1;return JSON.stringify(analysis())});const validResult=await valid.orchestrator.run(input('recValid'),env());assert.strictEqual(calls,1);assert.strictEqual(validResult.processingState,'Coincide preliminarmente');assert.strictEqual(validResult.decision.preliminaryMatch,true);assertNoAction(validResult);const replay=await valid.orchestrator.run(input('recValid'),env());assert.strictEqual(replay.replayed,true);assert.strictEqual(calls,1);assert.strictEqual(valid.proofWrites,1);assertNoAction(replay);
 calls=0;const exact=setup(async()=>{calls+=1;return JSON.stringify(analysis())});const exactResult=await exact.orchestrator.run(input('recDup',{duplicateReports:[{id:'old',sha:'a'.repeat(64)}]}),env());assert.strictEqual(calls,0);assert.strictEqual(exactResult.processingState,'Duplicado detectado');assertNoAction(exactResult);
 calls=0;const retry=setup(async({attempt})=>{calls+=1;if(attempt===1)throw Object.assign(new Error('timeout'),{code:'TIMEOUT'});return JSON.stringify(analysis())});const retryResult=await retry.orchestrator.run(input('recRetry',{config:{aiEnabled:true,primaryModel:'primary',maximumPrimaryRetries:1,minimumConfidence:0.85,promptVersion:'PROMPT_V2'}}),env());assert.strictEqual(calls,2);assert.strictEqual(retryResult.processingState,'Coincide preliminarmente');assert.strictEqual(retryResult.analysis.audit.length,2);assertNoAction(retryResult);
 calls=0;const secondary=setup(async({role})=>{calls+=1;return role==='primary'?'{bad':JSON.stringify(analysis())});const secondaryResult=await secondary.orchestrator.run(input('recSecondary',{config:{aiEnabled:true,primaryModel:'primary',secondaryEnabled:true,secondaryModel:'secondary',minimumConfidence:0.85,promptVersion:'PROMPT_V2'}}),env());assert.strictEqual(calls,2);assert.strictEqual(secondaryResult.processingState,'Coincide preliminarmente');assert.strictEqual(secondaryResult.analysis.rawPrimary,'{bad');assert(secondaryResult.analysis.rawSecondary.includes('COMPLETED'));assertNoAction(secondaryResult);
 const conflict=setup(async()=>JSON.stringify(analysis()));await conflict.orchestrator.run(input('recConflict'),env());const changed=await conflict.orchestrator.run(input('recConflict',{attachment:{sha:'b'.repeat(64),content:'other'}}),env());assert.strictEqual(changed.ok,false);assert.strictEqual(changed.reason,'PROCESSING_IDEMPOTENCY_CONFLICT');assertNoAction(changed);
 const source=fs.readFileSync(path.join(__dirname,'..','netlify','functions','_payment_processing_orchestrator.js'),'utf8');assert(!/airtableCreateRecord|airtablePatchRecord|syncOwnerAccess|mkjSetMemberStatus/.test(source));
 console.log('PAYMENT_PROCESSING_ORCHESTRATOR_OK');
})().catch(error=>{console.error(error);process.exit(1)});
