'use strict';
const assert=require('assert');
const fs=require('fs');
const page=fs.readFileSync('seguridad.html','utf8');
const backend=fs.readFileSync('netlify/functions/admin-security.js','utf8');
assert(page.includes('id="current-password"'),'El cambio de contraseña debe confirmar la contraseña actual.');
assert(page.includes("localStorage.getItem('vla-admin-token')"),'Seguridad debe reutilizar la sesión compartida para abrir la pantalla.');
assert(page.includes("post({action:'changePassword',currentPassword:document.getElementById('current-password').value,newPassword:a})"),'El cambio debe enviar la confirmación actual mediante el flujo protegido.');
assert(page.includes("params.get('reset')"),'La recuperación pública debe mantenerse.');
assert(backend.includes("if (action === 'changePassword')"));
assert(backend.includes('const auth = requireAdmin(event)'),'El cambio debe exigir token administrativo válido.');
assert(backend.includes('verifyPassword(body.currentPassword, config)'),'El backend debe verificar la contraseña actual.');
assert(backend.includes('Debe indicar la contraseña actual.'));
assert(backend.includes('La contraseña actual no es correcta.'));
console.log('SECURITY_SINGLE_SESSION_OK');
