'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');
const breakdown=require('../owner-breakdown-v7');const release=require('../release.json');
assert.strictEqual(release.release,'2026-08-21-v14');assert.strictEqual(release.expectedHouses,15);assert.strictEqual(release.breakdownPresentation,'owner-breakdown-v7');
const source=fs.readFileSync(path.join(__dirname,'../owner-breakdown-v7.js'),'utf8');for(const forbidden of ['Saldo USD Actual','Saldo Bs Ref Actual','Saldo Total Actual','window.calc','setTimeout','setInterval','MutationObserver','currentOwner'])assert(!source.includes(forbidden),`El desglose no debe depender de ${forbidden}`);
for(const required of ['Deuda del Mes Anterior','Beneficio Pronto Pago','Total Pagado','Costo<br>Total','Su<br>Parte'])assert(source.includes(required),`Falta ${required}`);
const owner={id:'casa-1',Casa:1,Alicuota:.07994,'Deuda Anterior':65},data={gastos:[{fields:{Concepto:'Vigilancia',Monto:1000,'Tipo de Gasto':'Gasto Común','Forma de Pago':'Bs BCV',Propietarios:[]}},{fields:{Concepto:'Gasoil',Monto:85,'Tipo de Gasto':'Gasto Especial','Forma de Pago':'USD',Propietarios:['casa-1']}}],pagos:[{fields:{'Propietario que Paga':['casa-1'],'[x] Aplicado al Cierre':false,'Equivalente USD Aplicado':66}}]};
function render(day){const host={className:'',innerHTML:'',attrs:{},setAttribute(k,v){this.attrs[k]=v}},title={textContent:''};assert(breakdown.render({owner,data,host,title,day,dueDay:10,monthLabel:'julio de 2026',formatUsd:n=>'$'+Number(n).toFixed(2)}));return{host,title}}
const before=render(1);assert.match(before.host.innerHTML,/VIGILANCIA/);assert.match(before.host.innerHTML,/\$1000\.00/);assert.match(before.host.innerHTML,/\$79\.94/);assert.match(before.host.innerHTML,/GASOIL/);assert.match(before.host.innerHTML,/Beneficio Pronto Pago/);assert.match(before.host.innerHTML,/- \$7\.99/);assert.strictEqual(before.title.textContent,'Desglose de Cargos para julio de 2026');
const after=render(11);assert.doesNotMatch(after.host.innerHTML,/Beneficio Pronto Pago/);assert.strictEqual(after.host.attrs['data-vla-breakdown-host'],'owner-breakdown-v7');console.log('VISUAL_BREAKDOWN_V7_TESTS_OK');
